### ISSUE TITLE
Problem with Estimate shipping & Tax

### ISSUE THREAD

**Issue by 123Dragon** [trydalcoholic/opencart-materialize#1]
In route=checkout/cart, Estimate shipping & Tax, the drop down for Region / State doesn't work. 

![image](https://cloud.githubusercontent.com/assets/29109935/26660032/43e34936-4643-11e7-926d-c1454a3df8ae.png)

**Comment by trydalcoholic** [comment]
Thank you for reporting errors.
The last update solved this problem, but it requires verification.
I would be happy if you report the results 😏.

**Comment by 123Dragon** [comment]
Thank you very much, the drop down works perfectly now.
