### ISSUE TITLE
Wrong URL in ld+json on header.tpl page

### ISSUE THREAD

**Issue by Sellato** [trydalcoholic/opencart-materialize#12]
Hi there!

Glad to meet you. Check please the URL in header.tpl
"target": "https://materialize.myefforts.ru/index.php?route=product/search&search={query}",
---------------------
	{
		"@context": "http://schema.org",
		"@type": "WebSite",
		"url": "<?php echo $base; ?>",
		"name": "<?php echo $title; ?>",
		<?php if ($description) { ?>
		"alternateName": "<?php echo $description; ?>",
		<?php } ?>
		"potentialAction": {
			"@type": "SearchAction",
			"target": "https://materialize.myefforts.ru/index.php?route=product/search&search={query}",
			"query-input": "required name=query"
		}
	}
	</script>
---------------------------------------
I think this is wrong :)

In Russian:

Добрый день!
Очень понравилась ваша тема. Редко встретишь из коробки ld+json, shema.org, скрипты и стили минимизированные и собраные в один файл.
Короче, я восхищен столь грамотным и продуманным отношением к времени загрузки магазина и SEO!

А вот в header.tpl неверно указана ссылка. Возможно нужна переменная, но мне кажется формат ld+json не допускает переменных. Если так, думаю нужно отразить в документации, что нужно изменить URL руками.

Спасибо, подписался на вас.

**Comment by trydalcoholic** [comment]
Спасибо, рад стараться!
Такой же вопрос уже поднимался в #9, скоро будет исправлено.
