### ISSUE TITLE
Is it possible to add hover and active effect to chips ?

### ISSUE THREAD

**Issue by Sellato** [trydalcoholic/opencart-materialize#15]
Hi!

Is it possible to add hover and active effect to chips ?

Добрый день!
Возможно ли добавить эффекты ( смена цвета при наведении и когда активный) для "чипсов" уж больно они скучные :)

Thanks.

**Comment by trydalcoholic** [comment]
Здравствуйте!
Вы можете самостоятельно переделывать всё под ваш вкус.
Конкретно для chips, пропишите в файле style.css примерно такую конструкцию: `.chip:hover {background:red !important;}`. В данном случае, `!important` обязателен.
Сценария, при котором chips могут быть активными я не припомню.
