### ISSUE TITLE
Button "add to card" move up if discount enabled

### ISSUE THREAD

**Issue by Sellato** [trydalcoholic/opencart-materialize#16]
If discont enabled the "add to cart" button move upp across the discription of the product.

Опять я, со своей "эстетикой".
Проблема вот в чем. Если у товара есть скидка, появляется новое поле и кнопка "добавить в корзину" уползает вверх и перекрывает описание товара.

Это конечно не большая беда, но мы ведь делаем идеальную тему :)
Спасибо.

[<img src="https://preview.ibb.co/iMT6kF/basket1.jpg" alt="basket1" border="0">](url)

**Comment by trydalcoholic** [comment]
Здесь приходится идти на компромисс со множеством факторов:
- множество различных разрешений экранов;
- учёт возможности использования дополнительных модулей согласно макетам в OpenCart;
- длина названий товаров;
- наличие и отсутствие скидки у товаров;
- опция вывода цен с указанием налогов.
Поэтому, на мой взгляд, используется наиболее гибкое решение на все случаи.
