### ISSUE TITLE
free_checkout.tpl button doesn't show text

### ISSUE THREAD

**Issue by 123Dragon** [trydalcoholic/opencart-materialize#18]
I implemented free checkout (zero value item in the cart) and during checkout, the button to submit the order didn't have any text.

I replaced in free_checkout.tpl:
`<button type="button" value="<?php echo $button_confirm; ?>" id="button-confirm" class="btn waves-effect waves-light red"></button>`

With
`<input type="button" value="<?php echo $button_confirm; ?>" id="button-confirm" class="btn waves-effect waves-light red" data-loading-text="<?php echo $text_loading; ?>" />`

Now it works perfectly:
![image](https://user-images.githubusercontent.com/29109935/28431711-429591ce-6d53-11e7-8bde-d31fb69cbaab.png)

**Comment by trydalcoholic** [comment]
Indeed, there was no text in the button. Thank you for discovering this and trying to fix it. In the nearest update the text will return to the place :).
