### ISSUE TITLE
opencart-materialize 3.х

### ISSUE THREAD

**Issue by lavlan** [trydalcoholic/opencart-materialize#19]
При переходе в Контакты  и Личный кабинет из шапки пишет
Контакты                                           : Личный кабинет
Сравнение товаров                         :  Сравнение товаров
Карта                                                 :дальше все как и в версии 2,3.х
дальше все как и в версии 2,3.х

З.Ы. Руссифицировал файл OCMOD по принципу 2.3.х

**Comment by trydalcoholic** [comment]
Не совсем понимаю, что вы имеете в виду. Пришли пожалуйста скриншот. Также укажите пожалуйста версию OpenCart, так как уже вышло их довольно много и в каждой множество различных ошибок 😵.

**Comment by lavlan** [comment]
Доброго времени суток поставил на хостинг можно в живую посмотреть...
[Версия 3.0.2.0 ](http://forum.opencart-russia.ru/threads/russkaja-sborka-opencart-3-0-2-0-reliz.5561/)
[Контакты](http://safsys.ru/index.php?route=information/contact)
[Личный кабинет](http://safsys.ru/index.php?route=account/login)

**Comment by trydalcoholic** [comment]
Теперь понял. К сожалению, это проблема самого OpenCart, конкретно версии 3.0.2.0. Если открыть, например, категорию, в которой нет товара, то появится сообщение о пустой корзине, вместо сообщения, что в данной категории нет товара 😒.  
Чуть ранние версии OpenCart 3.x не содержат таких ошибок, также как и более свежие сборки. Но ошибок всё ещё очень много, поэтому версия шаблона для третьей версии архивно лежит на гитхабе и не появляется в релизе, до лучших времён.

**Comment by lavlan** [comment]
Понял спасибо, а планируете ли настройку шаблона из админки?

**Comment by trydalcoholic** [comment]
Да, но пока только в планах. На очереди ещё несколько модулей.

**Comment by lavlan** [comment]
вот такой костыль
строку 59 `<!--<h1>{{ heading_title }}</h1>-->` закомментировал и добавил 
		`<h3>{{ text_location }}</h3>` 
[Контакты](http://safsys.ru/index.php?route=information/contact)

**Comment by trydalcoholic** [comment]
Костылей, действительно, можно много наделать и исправить ситуацию, но это получится отдельная версия шаблона только для версии 3.0.2.0.
Поэтому, когда выйдет стабильная версия 3-го OpenCart'а, появится полная поддержка, без костылей. Соответственно, версии 3.0.2.0 и ниже формально поддерживаться не будут 👐.

**Comment by MrElvys** [comment]
Здравствуйте! Подскажите какие файлы нужно скопировать в уже существующий сайт, чтобы установить новый модуль обратного звонка https://materialize.myefforts.ru/updates/new-callback ? Версия ocStore 2.3.0.2.3. Спасибо!

**Comment by trydalcoholic** [comment]
**Обязательно сделайте бекап.**
Удалите следующий файл: 
`catalog/view/theme/materialize/call_back.php`

Скопируйте следующие файлы в соответствующие им категории:
- `admin/controller/extension/module/callback.php`
- `admin/language/ru-ru/extension/module/callback.php` (для русского языка, соответственно)
- `admin/view/template/extension/module/callback.tpl`
- `catalog/controller/extension/module/callback.php`
- `catalog/language/ru-ru/extension/module/callback.php`
- `catalog/language/ru-ru/mail/callback.php`
- `catalog/model/extension/module/callback.php`
- `catalog/view/theme/materialize/template/extension/module/callback.tpl`

В файле **`catalog/view/theme/materialize/template/common/footer.tpl`** после строки `<script defer src="catalog/view/theme/materialize/js/script.js"></script>` должны остаться только закрывающие теги `</body></html>`, то есть, надо удалить старый скрипт вызова обратного звонка. 

В файле **`catalog/view/theme/materialize/template/common/header.tpl`** после строки `<?php echo $cart; ?>` добавлена новая строка `<?php echo $callback; ?>`.

**Также были изменены две строки.**
`<li><a class="blue-grey-text text-lighten-5 modal-call-back-btn activator" rel="nofollow"><?php echo $text_call_back; ?><i class="material-icons left">phone_in_talk</i></a></li>`

_Заменена на:_
`<li><a class="blue-grey-text text-lighten-5 modal-trigger activator" href="#callback__modal" rel="nofollow"><?php echo $text_call_back; ?><i class="material-icons left">phone_in_talk</i></a></li>`

**Эта строка**
`<li class="grey lighten-4"><a class="waves-effect waves-default modal-call-back-btn activator" rel="nofollow"><i class="material-icons">phone_in_talk</i><?php echo $text_call_back; ?></a></li>`

_заменена на:_
`<li class="grey lighten-4"><a class="waves-effect waves-default modal-trigger activator" href="#callback__modal" rel="nofollow"><i class="material-icons">phone_in_talk</i><?php echo $text_call_back; ?></a></li>`

И последнее, в файл установочный файл `materialize_theme.ocmod.xml` был добавлен этот код:
```
<file path="catalog/controller/common/header.php">
	<operation error="log">
		<search><![CDATA[$data['name'] = $this->config->get('config_name');]]></search>
		<add position="after"><![CDATA[
		$data['callback'] = $this->load->controller('extension/module/callback', $data);
		]]></add>
	</operation>
</file>
```
