### ISSUE TITLE
Shipping method selection doesn't work

### ISSUE THREAD

**Issue by 123Dragon** [trydalcoholic/opencart-materialize#2]
In /index.php?route=checkout/checkout, you cannot select the different methods. In this example, I cannot select the Canada post shipping.

![image](https://cloud.githubusercontent.com/assets/29109935/26660144/f5ff493a-4643-11e7-84b6-8bb6fc8f827b.png)

**Comment by trydalcoholic** [comment]
Thank you for reporting errors.
The last update solved this problem, but it requires verification.
I would be happy if you report the results 😏.

**Comment by 123Dragon** [comment]
Tested with new version, works perfectly, thank you.
![image](https://cloud.githubusercontent.com/assets/29109935/26686235/57130b78-46ba-11e7-8891-5441269a49c1.png)
