### ISSUE TITLE
About friendly url

### ISSUE THREAD

**Issue by merktan** [trydalcoholic/opencart-materialize#23]
When i looking your demo your opening page www.site.com . When push the your website icon, your website still www.website.com .

But in my website when i'm connect www.site.com . When i push the icon it will be https://website.com/index.php?route=common/home .

How can i fix this :  https://website.com/index.php?route=common/home     to     https://website.com.

Thank you for supporting .

**Comment by merktan** [comment]
i have one more questions. I have to fix this but i don't know how can.
you can see : sanatbuya.com     there is some problem about that.
but i click the icon it will be : https://sanatbuya.com/index.php?route=common/home  and every thing is okey. how can i fix this. 

Thank you for supporting.

**Comment by trydalcoholic** [comment]
The demo site uses SEO Pro, it immediately removes unnecessary text from the url. You can use a special module, for example this one: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=27700

**Comment by merktan** [comment]
You are the best one. Thank you.
