### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by rumi55** [trydalcoholic/opencart-materialize#24]
Hello,

I think you shold use google maps on information/contact instead yandex maps because yandex donnt showing maps from my country.

Thanks

**Comment by trydalcoholic** [comment]
Hello!
Thanks for the suggestion, Google Maps will definitely be added in future updates 🙃.

**Comment by trydalcoholic** [comment]
In the latest updates, a module with template settings was added. Including there are settings for Maps 🙌.
After testing and releasing the assembly of a new version of the template, this topic will be closed.
