### ISSUE TITLE
Вопросы по настройке шаблона

### ISSUE THREAD

**Issue by Pozitivchik** [trydalcoholic/opencart-materialize#25]
Добрый день. В процессе настройки шаблона "под себя" возникли следующие вопросы. Буду очень благодарен если Вы поможете с ними разобраться.
1. Как сопоставить размер бокового банера размеру отображаемой картинке, у меня всегда остаётся белая рамка по краям и как бы я не менял соотношения ширины и высоты проблема не решается.
2. Как изменить ширину колонок товара который отображается на странице категорий? Колонки товара сделать уже чтобы они отображались в 3 ряда (вместо двух по умолчанию).
3. Как на странице продукта (в верхней боковой части страницы) вывести модель товара?
4. Как добавить карту гугл вместо яндекса в разделе контактов?
P.S. Спасибо за шаблон, среди множества существующих считаю это более оптимальный вариант для интернет магазина на opencart.
_______________________________________________________________________________________________________________
Good afternoon. During the process of setting up the template "for yourself" the following questions arose. I will be very grateful if you will help to sort them out.
How to compare the size of the side banner to the size of the displayed image, I always have a white border around the edges and how I would not change the width and height ratio the problem is not solved.
How do I change the column width of a product that appears on the category page? Columns of the goods to make already that they were displayed in 3 rows (instead of the two by default).
How do I display a product model on the product page (at the top of the page)?
How do I add a Google map instead of Yandex in the contacts section?
P.S. Thanks for the template, among the many existing ones, I think this is the best option for an online store on opencart.

**Comment by rumi55** [comment]
@Pozitivchik I think you should writte on english so everybody can understand what are you asking. Thanks

**Comment by trydalcoholic** [comment]
Здравствуйте @Pozitivchik! Спасибо за ваш отзыв!

1. Приведите пожалуйста пример на вашем сайте.
2. Конкретно для страницы категорий нужно отредактировать этот файл: catalog/view/theme/materialize/template/product/category.twig
2.1. Для OC3 измените эту строчку:
`{% set main, goods = 's12 l9', 's12 m6' %}`
на
`{% set main, goods = 's12 l9', 's12 m6 l4' %}`.
`l4` — позволит на больших экранах занимать 4 из 12 строк сетки, т.е., 3 сниппета товара в строке.
2.2. В том же файле найдите и измените эту строку:
`<a href="{{ product.href }}"><img class="lazyload" src="{{ img_loader }}" data-src="{{ product.thumb }}" alt="{{ product.name }}" title="{{ product.name }}"></a>`
на
`<a href="{{ product.href }}"><img class="responsive-img lazyload" src="{{ img_loader }}" data-src="{{ product.thumb }}" alt="{{ product.name }}" title="{{ product.name }}"></a>`
3. Отредактируйте следующий файл: catalog/view/theme/materialize/template/product/product.twig. Найдите строку `{% if category_products %}` и **перед** ней добавьте эту строку `<li><span class="text-bold">{{ text_model }}</span>:&nbsp;<span>{{ model }}</span></li>`. Нужно ли там выводить дополнительное двоеточие я не знаю, в различных переводах и версия OC3 двоеточие то есть, то нет.
4. 4.1. Получить Google API Key по этой ссылке: https://developers.google.com/maps/documentation/javascript/get-api-key
4.2. Откройте и измените файл: catalog/view/theme/materialize/template/information/contact.twig
4.3. Строку `<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU"></script>` замените на `<script src="//maps.googleapis.com/maps/api/js?key=GOOGLE_API_KEY"></script>` (подставьте ваш ключ в скрипт)
4.4. Следующий код:
`ymaps.ready(init);
function init() {
	var myMap = new ymaps.Map('map', {
		center: [55.753994, 37.622093],
		zoom: 16,
		controls: []
	});
	ymaps.geocode('{{ address }}', {
		results: 1
	}).then(function (res) {
		var firstGeoObject = res.geoObjects.get(0),
		coords = firstGeoObject.geometry.getCoordinates(),
		bounds = firstGeoObject.properties.get('boundedBy');
		myMap.geoObjects.add(firstGeoObject);
		myMap.setBounds(bounds, {
			checkZoomRange: true
		});
	});
};`
замените на:
`function initialize_map() {
	var LAT_LNG = new google.maps.LatLng({{ geocode }});
	var mapOptions = {
		center: LAT_LNG,
		zoom: 16
	};
	var map = new google.maps.Map(document.getElementById("map"), mapOptions);
	var marker = new google.maps.Marker({
		position: LAT_LNG,
		map: map
	});
}
google.maps.event.addDomListener(window, 'load', initialize_map);`
4.5. Строку `<div id="map">` замените на `<div id="map" style="width:100%;height:360px;">`

@rumi55 can i short translation into english do 😃?
Find file
🙃🙃
Find String
🙃🙃
Replace with another string

P.S. At this point in the development of a template management module, in which you can select the type of cards for the contact page and various other settings. So, soon it can be done simply in the admin panel.

**Comment by Pozitivchik** [comment]
Спасибо за столь подробный ответ. 
1. Вот пример того как изображение не занимает 100% места в области банера. При этом я пытался подстраивать ширину и высоту самого банера под загруженное изображение. 

![12345](https://user-images.githubusercontent.com/33651511/32851100-bb989d50-ca3c-11e7-97b6-439dae96a6d6.png)

2. Подскажите пожалуйста, а для версии opencart_2.3.x какие изменения нужно внести, чтобы товары отображались в три столбца? Я попытался `<?php $main = 's12 l9'; $goods = 's12 m6'; ?>` изменить на `<?php $main = 's12 l9'; $goods = 's12 m6 x14'; ?>` и `<a href="<?php echo $product['href']; ?>"><img class="lazyload" src="<?php echo $img_loader; ?>" data-src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>"></a>` на `<a href="<?php echo $product['href']; ?>"><img class="responsive-img lazyload" src="<?php echo $img_loader; ?>" data-src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>"></a>` Но эти изменения оказались безрезультатными. Если Вас не затруднит напишите пожалуйста что я сделал не так. Ещё важно упомянуть, что я стремлюсь вывести товар в три ряда с учётом того что с боку страницы отображается блок с банером. 
3. Очень интересно Ваше мнение какой CMS лучше отдать предпочтение  ocStore 2.3.0.2.3 или OC3? Учитывая что мой интернет ресурс рассчитан на русскоязычных пользователей.
-------------------------------------------------------------------------------------------------------------------
Thank you for such a detailed answer.
1. Here is an example of how the image does not take 100% of the place in the banner area. In doing so, I tried to adjust the width and height of the banner itself to the uploaded image.

2. Prompt please, and for version opencart_2.3.x what changes it is necessary to make, that the goods were displayed in three columns? I tried `<?php $main = 's12 l9'; $goods = 's12 m6'; ?>` change to `<?php $main = 's12 l9'; $goods = 's12 m6 x14'; ?>` and  `<a href="<?php echo $product['href']; ?>"><img class="lazyload" src="<?php echo $img_loader; ?>" data-src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>"></a>` to `<a href="<?php echo $product['href']; ?>"><img class="responsive-img lazyload" src="<?php echo $img_loader; ?>" data-src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>"></a>` But these changes were unsuccessful. If you do not mind please write what I did wrong.

**Comment by rumi55** [comment]
Thank you for translating this.

**Comment by trydalcoholic** [comment]
@Pozitivchik 
1. 1.1. Download this file for yourself: https://yadi.sk/d/a_2txR9T3PmkGf and replace it along this path: catalog/view/theme/materialize/template/extension/module/banner.tpl
1.2. In the Banner settings for the image, set a minimum of 300 pixels in width, and the height is proportional to your image
2. You specified the number 1, instead of the letter l 🙂. `<?php $main = 's12 l9'; $goods = 's12 m6 xl4'; ?>` — here is the correct code. s, m, l, xl - as the sizes of clothes, for example.
3. Due to the built-in SEO Pro in OCStore, I think it's preferable.

**Comment by Pozitivchik** [comment]
@trydalcoholic 
Приветствую Вас, Антон. Предложенное Вами решение оказалось очень полезным в исправлении проблемы с банером, так же с Вашей помощью решил задачу с выводом товара в три колонки на страницах категории. За что Вам особая благодарность. В ходе работы с шаблоном есть некоторые нюансы на которые прошу обратить Ваше внимание. 
1. В админ панели на странице шаблона в title отображается следующий код: `<title><font color="#263238"><b><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Materialize Template</b></font></title>`. На сколько я понимаю это может быть следствием не корректного sql запроса в БД при установки шаблона. 
2.  В боковом вертикальном меню "Категории", при развертывании, сбоку на несколько секунд появляется вертикальная полоса прокрутки. Не смотря на то, что она быстро исчезает это всё равно заметно глазу пользователя. Как можно удалить эту полосу?
3. Всплывающие окна типа "Товар добавлен в корзину" отображаются около семи секунд, как можно сократить время отображения таких уведомлений?
Ещё раз благодарю Вас за такой практичный и универсальный шаблон. Сегодня тестировал сайт на гугле. Результат: "...находится на одном уровне с наиболее эффективными сайтами..." Я считаю, что это во многом благодаря и шаблону  "opencart-materialize".
-------------------------------------------------------------------------------------------------------------------
@trydalcoholic
Greetings. The solution proposed by you turned out to be very useful in correcting the problem with the banner, and with your help solved the problem with the output of goods in three columns on the category pages. For which you are particularly grateful. In the course of working with the template there are some nuances for which I ask you to pay your attention.
1. The following code is displayed in the admin panel on the template page in title: `<<title> <font color = "# 263238"> <b> <i class = "fa fa-cogs" aria-hidden = "true" i> & nbsp; & nbsp; & nbsp; Materialize Template </ b> </ font> </ title> `. As far as I understand this may be a consequence of a wrong sql query in the database when installing the template.
2. In the side vertical menu "Categories", when deployed, a vertical scrollbar appears for a few seconds. Despite the fact that it quickly disappears, it is still noticeable to the user's eye. How can I remove this strip?
3. Pop-up windows of the type "Product added to the cart" are displayed for about seven seconds, how can I reduce the time for displaying such notifications?
Once again I thank you for such a practical and universal template. Today I tested the site on Google. The result: "... is on par with the most effective sites ..." I believe that this is largely due to the "opencart-materialize" template.

**Comment by trydalcoholic** [comment]
1. It has already been fixed, but thank you for informing me.
2. Unfortunately, you can not get rid of the scroll bar. In future updates, a different menu will be used, which in principle solves the problem.
3. Open the catalog catalog/view/theme/materialize/js/script.js file and edit the line `Materialize.toast('<span><i class="material-icons left">check</i>'+json['success']+'</span>',7000,'toast-success');`. 7000 is the time to display the notification, in milliseconds.

**Comment by Pozitivchik** [comment]
1. А как у себя в админке исправить title?
2. Подскажите пожалуйста, как изменить расстояние (сделать уже) между блоками товаров отображаемых на главной странице?
![22222](https://user-images.githubusercontent.com/33651511/33033365-d2515a98-ce2c-11e7-8868-3f82ba96fc17.png)

**Comment by trydalcoholic** [comment]
1. Обновите следующие файлы:
1.1. admin/controller/extension/theme/materialize.php
1.2. admin/language/ru-ru/extension/theme/materialize.php
1.3. admin/view/template/extension/theme/materialize.tpl
2. Отредактируйте файлы соответствующих модулей:
2.1. catalog/view/theme/materialize/template/extension/module/bestseller.tpl
2.2. catalog/view/theme/materialize/template/extension/module/featured.tpl
2.3. catalog/view/theme/materialize/template/extension/module/latest.tpl
2.4. catalog/view/theme/materialize/template/extension/module/special.tpl
`<section class="section href-underline">` — для блока section удалите **класс** section или пропишите свои собственные.
