### ISSUE TITLE
There's no style in main page

### ISSUE THREAD

**Issue by g-dogg** [trydalcoholic/opencart-materialize#26]
Hello

I've been installed the theme how as described in pdf manual. But site looks like style.css didn't load. I have no idea how fix it. 
Image: https://snag.gy/ZuvkfD.jpg

**Comment by g-dogg** [comment]
I'm stupid. I figured out how to fix it and done. Thank you

**Comment by trydalcoholic** [comment]
Hi!
Ok. I'll venture to assume that you forgot to update the module cache in the admin panel. If suddenly someone else encounters a similar problem.
