### ISSUE TITLE
Не обновляется

### ISSUE THREAD

**Issue by ShakhGani** [trydalcoholic/opencart-materialize#27]
Здравствуйте! У меня возникли проблемы.
1. Когда редактирую header или footer, а затем обновляю модификатора, то ничего не обновляется на сайте. Если посмотреть с помощью "Посмотреть кода страницы" браузера, то видно, что ничего не добавлено/убрано
2. Когда захожу на определенную категорию, а там надпись "Ваша корзина пуста", но суть не в этом, а в том что товары на подкатегории не выводится на самой категории. Например: Есть категория "Samsung" и внутри подкатегория "S-series". Есть товар на подкатегории "S-series". По логике этот товар должен выводится и на категории "Samsung", и на подкатегории "S-series". Посмотрел ваш демо сайт и там как раз это есть. Но у себя не наблюдаю такую функцию.
Сайт на ОС 3.0.2.0
Спасибо заранее :+1:

**Comment by trydalcoholic** [comment]
Это не связано с работой шаблона. Тем не мене, в OpenCart 3.0.2.0:
1. Кэширование шаблона отключается на главной странице панели администратора. Нажмите на настройки (шестерёнка в правом верхнем углу). Во всплывающем окне выберите либо Refresh, чтобы применить ваши изменения, либо отключите кэширование вовсе, затем снова нажмите Refresh
2. При добавлении/редактировании товара в панели администратора, во вкладке Links (Связи) указываются категории в которых выводить товар. В вашем случае просто укажите несколько категорий: Samsung и Samsung > S-series.

**Comment by ShakhGani** [comment]
Спасибо. Проблема была в самой движке. Переходил с 3.0.2.0 на 2.3 и все заработало
