### ISSUE TITLE
backend editor

### ISSUE THREAD

**Issue by aarontower** [trydalcoholic/opencart-materialize#28]
Hello appreciation for your excellent work.

I have a problem with the back-end editor. When insert image, it add a fixed width style, and in code view i can not remove this width style or add class for elements. How to return the original editor? 

![qq 20171124104516](https://user-images.githubusercontent.com/33935789/33194145-c1a055f8-d108-11e7-814f-b26af1c13bfd.png)

**Comment by trydalcoholic** [comment]
Hello!

Please do not ask any more questions like this. This has nothing to do with the work of the template. You take time, distract me from work and prevent me from finding the real problems associated with the work of the Materialize template.

If you are editing the original code, just click the "View code" button again to accept the changes.

Henceforth, I will be forced to close similar Issue without explaining the reasons.

**Comment by aarontower** [comment]
Hello, i means the modification can not be saved, after i remove the code `style="width: 1037px;"`  and click save button, it appears again.

**Comment by aarontower** [comment]
This is tested in 2.3 version
