### ISSUE TITLE
Обратный звонок

### ISSUE THREAD

**Issue by ShakhGani** [trydalcoholic/opencart-materialize#29]
Здравствуйте! Я включил модуль "Обратный звонок". Вот например кто-то оставил свой номер. Где можно найти этот номер в админке? Спасибо

**Comment by trydalcoholic** [comment]
Здравствуйте!
Уведомления приходят на почту, в панели администратора не ведётся учёт.

P.S. Пожалуйста, больше ее задавайте подобных вопросов здесь, github необходим для оперативного выявления ошибок, связанных с работой шаблона и его модулей. Вопросы о том что и как работает, вы можете задавать мне по почте: gatalsky94@yandex.ru, В дальнейшем я вынужден закрывать подобные вопросы без объяснения причин.
