### ISSUE TITLE
Materialize Template убрать в footer или заменить

### ISSUE THREAD

**Issue by astengrau** [trydalcoholic/opencart-materialize#30]
Привет! Тема супер!!! Можешь пожалуйста помочь, можно ли поменять или вообще убрать с футера (Materialize Template) внизу справа?
Зарание СПАСИБО!

**Comment by ShakhGani** [comment]
/catalog/view/theme/materialize/template/common/footer.tpl если у тебя версия 2.х

**Comment by astengrau** [comment]
Я уже все варианты перепробовал и в footer.twig закомментировал и удалял, ничего не получается, и в стилях ставил display:none, ноль реакции, видимо где-то скрипт отрабатывает и не даёт изменить.

**Comment by trydalcoholic** [comment]
В OpenCart 3.0.2.0. шаблоны кэшируются. После каждого изменения Вы должны либо обновлять кэш в панели администратора, либо отключить его на время проведения работ над сайтом. Кэш обновляется через главную страницу панели администратора, через кнопку настроек (шестёрка в правом верхнем углу).

P.S. Пожалуйста, больше ее задавайте подобных вопросов здесь, github необходим для оперативного выявления ошибок, связанных с работой шаблона и его модулей. Вопросы о том что и как работает, вы можете задавать мне по почте: gatalsky94@yandex.ru, В дальнейшем я вынужден закрывать подобные вопросы без объяснения причин.
