### ISSUE TITLE
My account > Address book

### ISSUE THREAD

**Issue by aarontower** [trydalcoholic/opencart-materialize#31]
Hello, i found a small mistake
/upload/catalog/view/theme/materialize/template/account/address_form.tpl
`$('select[name=\'zone_id\']').html(html);`
please add this line below: `$('select').material_select();` 
or the region can not be selected

**Comment by trydalcoholic** [comment]
Hello!
It really needs to be done, thank you for reported an error!
In the next update, this fix will be added.
