### ISSUE TITLE
Problem this template

### ISSUE THREAD

**Issue by murat8505** [trydalcoholic/opencart-materialize#34]
This template is not compatible with 3.0.2.0
my site http://ashana.ayu.edu.kz/ocart
http://ashana.ayu.edu.kz/ocart/admin
user: admin
password: 123456

**Comment by trydalcoholic** [comment]
Please stop creating a new Issue!
This site is to search for technical problems, not to solve personal problems! Next time use the instruction!

**Comment by murat8505** [comment]
Made as written instructions but does not work

**Comment by murat8505** [comment]
please help me!
