### ISSUE TITLE
Список/сетка

### ISSUE THREAD

**Issue by cheromg** [trydalcoholic/opencart-materialize#35]
Добрый день! Как сделать вывод товаров списком по умолчанию

**Comment by trydalcoholic** [comment]
Здравствуйте!
Тема поддерживает вывод товара только сеткой.

**Comment by cheromg** [comment]
А в коде не где нельзя изменить?

**Comment by trydalcoholic** [comment]
В коде нечего изменять, так как вывод товара списком не поддерживается.
