### ISSUE TITLE
После обновления ошибка!

### ISSUE THREAD

**Issue by astengrau** [trydalcoholic/opencart-materialize#36]
Привет.
После обновления шаблона на версии 3.0.2.0 ошибка модуля Таблица размеров!
При отключении его он все равно активный, и при включении ничего не изменяется, до обновления все работало хорошо. Помоги пожалуйста разобраться с этим модулем.
Заранее спасибо.

**Comment by trydalcoholic** [comment]
Здравствуйте!
Обновление с какой версии и на какую вы совершаете?

**Comment by astengrau** [comment]
Я скачал последнюю версию с репозитория и обновил, и после этого.

**Comment by trydalcoholic** [comment]
Когда вы скачали последнюю версию?

**Comment by astengrau** [comment]
Вчера скачал в 12 часов дня

**Comment by trydalcoholic** [comment]
К этому моменту была удалена модульная зависимость для Таблицы размеров, теперь она встроена по умолчанию. Появилась новая вкладка "Таблица размеров" при редактировании товаров.
Остатки модуля надо удалить вручную:
- admin/controller/extension/module/sizechart.php
- admin/language/ru-ru/extension/module/sizechart.php (en-gb, ro-ro, tr-tr, ua-uk)
- admin/view/template/extension/module/sizechart.twig (.tpl)
- catalog/controller/extension/module/sizechart.php
- catalog/language/ru-ru/extension/module/sizechart.php (en-gb, ro-ro, tr-tr, ua-uk)
- catalog/view/theme/materialize/template/extension/module/sizechart.twig (.tpl)

**Comment by astengrau** [comment]
Можно тогда вопрос? Он всегда теперь будет по умолчанию? Его отключить нельзя?

**Comment by trydalcoholic** [comment]
В текущем виде нельзя отключить.

**Comment by astengrau** [comment]
Ясно спасибо.
