### ISSUE TITLE
Связка OcStore2.3.0.2.3 + Materialize opencart_2.3.x ошибка Google Maps

### ISSUE THREAD

**Issue by Andrikoss** [trydalcoholic/opencart-materialize#37]
Связка OcStore2.3.0.2.3 + Materialize opencart_2.3.x
Была проблема, при клике на кнопку карты, на странице контакты
открывалась карта с ошибкой "по вашему запросу ни чего не найдено"
При ближайшем рассмотрении оказалось что кнопка, вместо геокода
отправляла всего одну запятую. 
Поправил взяв часть кода из:
. . . . . /catalog/view/theme/default/template/information/**contact.tpl**
и вставил в:
. . . . . /catalog/view/theme/materialize/template/information/**contact.tpl**

Было в contact.tpl строка 64-65
`<?php if ($google) { ?>
						<a href="//maps.google.com/maps?q=<?php echo $lat; ?>,<?php echo $lng; ?>&hl=<?php echo $geocode_hl; ?>&t=m&z=15" class="btn-floating btn-large halfway-fab waves-effect waves-light blue" title="<?php echo $text_view_map; ?>" target="_blank" rel="noopener"><i class="material-icons">map</i></a>
						`
Стало: в contact.tpl строка 64-65

`<?php if ($geocode) { ?>
						<a href="https://maps.google.com/maps?q=<?php echo urlencode($geocode); ?>&hl=<?php echo $geocode_hl; ?>&t=m&z=15" class="btn-floating btn-large halfway-fab waves-effect waves-light blue" title="<?php echo $text_view_map; ?>" target="_blank" rel="noopener"><i class="material-icons">map</i></a>
`

Теперь все работает как положено.
Если кому поможет, рад от души.
Всех благ и с наступающим 2018
						`

**Comment by trydalcoholic** [comment]
Здравствуйте!
Спасибо что обратили внимание, но ничего править не надо.
В модуле Materialize Template Настройки, во вкладке карта для Google Maps необходимо заполнить 3 поля:
- Google API Key
- Координаты - Широта
- Координаты - Долгота

Эти поля обязательны для заполнения, хоть для координат это и не указано (фишка, а не баг (в будущем укажу обязательным)).

**Comment by Andrikoss** [comment]
Здравствуйте Семён!
Спасибо. 
Я тоже этот пункт не учел.
Ввел в стандартных настройках магазина координаты но выдавало ошибку
вот и влез в код. )) Хотя в коде ни бум бум.

Но есть еще нюанс ...
Opencart 3.0.2.0 и Materialize 3.x
В личном кабинете > сменить (добавить) адрес - не раскрывается список регионов.
Список стран работает, а вот список регионов нет.

Пробовал с разных браузеров, чистил кеш ни чего не помогло.
Поэтому поставил ocStore 2.3.0.2.3 и Materialize 2.x

К сожалению я уже все снес (Opencart 3.0.2.0 и Materialize 3.x)
а то так бы сделал видео или скриншоты что там не так.

Помогите пожалуйста решить этот вопрос и я с удовольствием 
вернусь на Opencart 3.0.2.0 и Materialize 3.x

P.S.
Даже стыдно что не разобравшись кинул сюда свои правки.
Множко стыдно, извините.

Заранее признателен. И еще раз спасибо за разъяснение по поводу карт.
С  Уважением  Андрей !
