### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by godunof** [trydalcoholic/opencart-materialize#38]
Когда клиент оформляет обратный звонок где он отображается? 
И еще вопрос как из карточки товара убрать блок "Оплата наличными и банковскими картами"

**Comment by godunof** [comment]
Помогите!!!!!!! При нажатии на Кнопку "Подтверждение заказа" нечего не происходит хотя в админке заказ отображается.

**Comment by trydalcoholic** [comment]
Заявки на обратный звонок приходят на почту, указанную в настройках магазина.
Если вы скачаете последнюю сборку шаблона с github, вы сможете также настроить панель инструментов на главной странице панели администратора:

- выдайте все права на редактирование и просмотр для группы администраторов;
- включите панель обратного звонка через "модули/расширения" -> "панель управления"

Убрать блок можно отредактировать соответствующий код в шаблоне странице товаров: catalog/view/theme/materialize/template/product/product.twig (tpl), какой именно код не могу подсказать, так как у меня уже нет исходников старой версии шаблона. В новой версии данный блок включается и отключается через модуль настроек шаблона, по умолчанию такого блока нет.

По последнему вопросу, пожалуйста, дайте больше информации. Какая у вас версия OpenCart? Какой модуль оплаты вы используете? Пришлите по возможности скриншоты.

**Comment by godunof** [comment]
После установки обновления когда нажимаю настройку шаблона вот такая ошибка
(*Fatal error*: Uncaught Exception: Error: Table
'cdagrom17250.oc_materialize_colors' doesn't exist<br />Error No: 1146<br
/>SELECT * FROM oc_materialize_colors ORDER BY name ASC in
/var/www/cdagrom17250/data/www/
agromost.com.ua/system/library/db/mysqli.php:40 Stack trace: #0
/var/www/cdagrom17250/data/www/agromost.com.ua/system/library/db.php(16):
DB\MySQLi->query('SELECT * FROM o...', Array) #1
/var/www/cdagrom17250/data/www/
agromost.com.ua/admin/model/extension/module/materialize.php(10):
DB->query('SELECT * FROM o...') #2
/var/www/cdagrom17250/data/www/storage/modification/system/engine/loader.php(185):
ModelExtensionModuleMaterialize->getMaterializeColors() #3
/var/www/cdagrom17250/data/www/agromost.com.ua/system/engine/proxy.php(25):
Loader->{closure}(Array, Array) #4 /var/www/cdagrom17250/data/www/
agromost.com.ua/admin/controller/extension/module/materialize.php(70):
Proxy->__call('getMaterializeC...', Array) #5
/var/www/cdagrom17250/data/www/storage/modification/system/engine/action.php(51):
ControllerExtensionModule in
*/var/www/cdagrom17250/data/www/agromost.com.ua/system/library/db/mysqli.php
<http://agromost.com.ua/system/library/db/mysqli.php>*on line *40)*

С уважением,
*ООО "Агромост Трейд"* запчасти к сельхозтехнике
Case New Holland John Deer *Horch*
+38(067)93-89-800
+38(096)92-69-436
+38(066)88-60-444
+38(099)04-15-531
+38(095)37-30-222
факс +38-06461-2-16-71
*agromost.in.ua*
<http://yandex.ua/clck/jsredir?bu=uniq15121098493642992024&from=yandex.ua%3Byandsearch%3Bweb%3B%3B&text=&etext=1622.r9Ngzh7H28NlF0Cre-byVJ044m39-5Er9FAlRrvOVCo_07GHPhVoyQEwaQoI0Z5-Xlg92ZLtM1c88PEmY-F3fQ.bdd0700e0244c7aecab02836997e278311abf773&uuid=&state=PEtFfuTeVD4jaxywoSUvtB2i7c0_vxGdjWT7Elao4JUWxZ-v0OIKpF-Jgk3I2xx3aYcU8ulqAAen3St6wKIDA2BPPObgm_Vu&&cst=AiuY0DBWFJ5fN_r-AEszkzIPwJvOwGiAKZyRwYR0GGrRbzh1cLiiJ2yZv8zu9l5He9fVMMRjlaDlcBHvKDxu0SD_VK79CaCZ9UCuVC8DEG1LZBrCOS9mGTaybCz_V_gDs0X9rBpLIQfFLK7AyS_ObeEUoQYZxVzopwb2164T1K6CLFcbrMRECPusz8cc77C19jt3xGNz6EM,&data=UlNrNmk5WktYejY4cHFySjRXSWhXQU94RldpUVEwSko0aldBSjY2RmNTbDF5c2c2a1ZNR3lCaE9aNDhRbDdqM1A4SVh3ck9laVJGYWUzcmQySW1ndGZWZHJWcFY5WTdT&sign=90b1f151dddf6211ca6e2756fc47a18f&keyno=0&b64e=2&ref=orjY4mGPRjmt1xzYuZsDZc0yXNZrdi6LvL-7TfwDljmtGW3-MAIsAZIcd3gXWo3WRcGB8YanJcYaH126c_qyZUZpHNXjEcD5KLvw-j4dRwrs2LWQhm9_H58h7Tp8sayDC6wjtQKVJ1Hto1nlo8sHu1VKiMXy_xe2XN10FLbKubLBGcNo2qc10w,,&l10n=uk&cts=1512125568203&mc=2>
agromost.com.ua

22 декабря 2017 г., 4:32 пользователь Anton Semenov <
notifications@github.com> написал:

**Comment by godunof** [comment]
Я вас уже наверное достал.
Переустановил шаблон все нормально кроме отображения шапки сайта. на
скринах видно.
И по поводу оформления заказа стоит выбран банковский перевод при нажатии
на кнопку на сайте нечего не происходит но в админке заказ видно.

С уважением,
*ООО "Агромост Трейд"* запчасти к сельхозтехнике
Case New Holland John Deer *Horch*
+38(067)93-89-800
+38(096)92-69-436
+38(066)88-60-444
+38(099)04-15-531
+38(095)37-30-222
факс +38-06461-2-16-71
*agromost.in.ua*
<http://yandex.ua/clck/jsredir?bu=uniq15121098493642992024&from=yandex.ua%3Byandsearch%3Bweb%3B%3B&text=&etext=1622.r9Ngzh7H28NlF0Cre-byVJ044m39-5Er9FAlRrvOVCo_07GHPhVoyQEwaQoI0Z5-Xlg92ZLtM1c88PEmY-F3fQ.bdd0700e0244c7aecab02836997e278311abf773&uuid=&state=PEtFfuTeVD4jaxywoSUvtB2i7c0_vxGdjWT7Elao4JUWxZ-v0OIKpF-Jgk3I2xx3aYcU8ulqAAen3St6wKIDA2BPPObgm_Vu&&cst=AiuY0DBWFJ5fN_r-AEszkzIPwJvOwGiAKZyRwYR0GGrRbzh1cLiiJ2yZv8zu9l5He9fVMMRjlaDlcBHvKDxu0SD_VK79CaCZ9UCuVC8DEG1LZBrCOS9mGTaybCz_V_gDs0X9rBpLIQfFLK7AyS_ObeEUoQYZxVzopwb2164T1K6CLFcbrMRECPusz8cc77C19jt3xGNz6EM,&data=UlNrNmk5WktYejY4cHFySjRXSWhXQU94RldpUVEwSko0aldBSjY2RmNTbDF5c2c2a1ZNR3lCaE9aNDhRbDdqM1A4SVh3ck9laVJGYWUzcmQySW1ndGZWZHJWcFY5WTdT&sign=90b1f151dddf6211ca6e2756fc47a18f&keyno=0&b64e=2&ref=orjY4mGPRjmt1xzYuZsDZc0yXNZrdi6LvL-7TfwDljmtGW3-MAIsAZIcd3gXWo3WRcGB8YanJcYaH126c_qyZUZpHNXjEcD5KLvw-j4dRwrs2LWQhm9_H58h7Tp8sayDC6wjtQKVJ1Hto1nlo8sHu1VKiMXy_xe2XN10FLbKubLBGcNo2qc10w,,&l10n=uk&cts=1512125568203&mc=2>
agromost.com.ua

22 декабря 2017 г., 4:32 пользователь Anton Semenov <
notifications@github.com> написал:

**Comment by trydalcoholic** [comment]
Скриншоты вы не прислали.
Проблема с перенаправлением при оплате банковским переводом действительно есть, спасибо что сообщили об этом!
Сейчас вы можете исправить проблему, отредактировав файл: catalog/view/theme/materialize/template/extension/payment/bank_transfer.twig
Найдите этот код:
`$('#button-confirm').on('click', function() {
	$.ajax({
		type: 'get',
		url: 'index.php?route=extension/payment/bank_transfer/confirm',
		cache: false,
		success: function() {
			if (json['redirect']) {
				location = json['redirect'];
			}
		},
		error: function(xhr, ajaxOptions, thrownError) {
			alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
	});
});`

и замените его на:

`$('#button-confirm').on('click', function() {
	$.ajax({
		url: 'index.php?route=extension/payment/bank_transfer/confirm',
		dataType: 'json',
		success: function(json) {
			if (json['redirect']) {
				location = json['redirect'];	
			}
		},
		error: function(xhr, ajaxOptions, thrownError) {
			alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
	});
});`
