### ISSUE TITLE
Не работает список регионов в личном кабинете Opencart 3.0.2.0(rs.3)+Materialize3x

### ISSUE THREAD

**Issue by Andrikoss** [trydalcoholic/opencart-materialize#39]
Opencart 3.0.2.0 и Materialize 3.x
В личном кабинете > сменить (добавить) адрес - не раскрывается список регионов.
Список стран работает, а вот список регионов нет.
Как быть?
![screenshot_1](https://user-images.githubusercontent.com/34532476/34277799-616a0be6-e6b8-11e7-9ae4-f40500911cff.png)
![screenshot_2](https://user-images.githubusercontent.com/34532476/34277800-619bd54a-e6b8-11e7-9f98-65f1ecd5d8a3.png)
![screenshot_3](https://user-images.githubusercontent.com/34532476/34277801-61cd1fba-e6b8-11e7-9cef-2a24f856f521.png)
![screenshot_4](https://user-images.githubusercontent.com/34532476/34277802-61f957ec-e6b8-11e7-92ed-28a63147e9a6.png)
![screenshot_5](https://user-images.githubusercontent.com/34532476/34277803-62257c82-e6b8-11e7-96dc-f4738cb6951d.png)
![screenshot_6](https://user-images.githubusercontent.com/34532476/34277804-6250e82c-e6b8-11e7-8eab-df59cd98a9b7.png)

**Comment by trydalcoholic** [comment]
Здравствуйте!
Спасибо что сообщили об этом.
Попробуйте отредактировать файл catalog/view/theme/materialize/template/account/address_form.twig таким образом.
Найдите эти строки:

- `$('select[name=\'zone_id\']').html(html);`
- `$('select[name=\'country_id\']').trigger('change');`

После каждой вставьте этот код: `$('select').material_select();`

**Comment by Andrikoss** [comment]
Здравствуйте!
Спасибо огромное, теперь все работает четко.
Видимо надо поправить этот файл и в раздаче шаблона.
Спасибо за помощь и качественный шаблон.
Всех благ и с наступающим.
С Уважением Андрей!
