### ISSUE TITLE
ocStore 2.3.0.2.3 + Materialize 2,3,х ошибка в модуле Materialize "Быстрый заказ"

### ISSUE THREAD

**Issue by Andrikoss** [trydalcoholic/opencart-materialize#40]
Здравствуйте обнаружил такую странность.
Подменяется текст в модуле быстрого заказа.
В пункте ( **Мною прочитаны и я даю согласие с документом** )
Помогите пожалуйста разобраться, может что то делаю не так???

![screenshot_1](https://user-images.githubusercontent.com/34532476/34295759-138265e6-e720-11e7-8c7f-a3528f485544.png)
![screenshot_2](https://user-images.githubusercontent.com/34532476/34295760-13bac1e8-e720-11e7-9713-316f787f380f.png)
![screenshot_3](https://user-images.githubusercontent.com/34532476/34295761-13ebd954-e720-11e7-98e9-3d7f2112e4ec.png)
![screenshot_4](https://user-images.githubusercontent.com/34532476/34295762-141e459c-e720-11e7-90d0-fbf434998026.png)
![screenshot_5](https://user-images.githubusercontent.com/34532476/34295763-144e8ee6-e720-11e7-838d-0690aba48872.png)
![screenshot_6](https://user-images.githubusercontent.com/34532476/34295764-147d7440-e720-11e7-8d83-598eb42d2e08.png)
![screenshot_7](https://user-images.githubusercontent.com/34532476/34295765-14b1a40e-e720-11e7-9cee-1808e8b34cbd.png)
![screenshot_8](https://user-images.githubusercontent.com/34532476/34295766-150a50d6-e720-11e7-98da-62652f1269a4.png)

**Comment by trydalcoholic** [comment]
Это ошибка в коде! Большое спасибо что сообщили. Та же проблема касается и модуля обратного звонка.
Вот быстрый способ это исправить. Отредактируйте следующие файлы: catalog/controller/extension/module/quickorder.php (callback.php)

Найдите эту строку: 

`$data['text_agree'] = sprintf($this->language->get('text_agree'), $this->url->link('information/information/agree', 'information_id=' . $this->config->get('config_account_id'), true), $information_info['title'], $information_info['title']);`

замените на:

`$data['text_agree'] = sprintf($this->language->get('text_agree'), $this->url->link('information/information/agree', 'information_id=' . $this->config->get('module_quickorder_agreement'), true), $information_info['title'], $information_info['title']);`

Для модуля обратного звонка, соответственно:

`$data['text_agree'] = sprintf($this->language->get('text_agree'), $this->url->link('information/information/agree', 'information_id=' . $this->config->get('config_account_id'), true), $information_info['title'], $information_info['title']);`

заменить на:

`$data['text_agree'] = sprintf($this->language->get('text_agree'), $this->url->link('information/information/agree', 'information_id=' . $this->config->get('module_callback_agreement'), true), $information_info['title'], $information_info['title']);`

Все исправленные проблемы я залью на github при первой возможности. Ещё раз спасибо!

**Comment by Andrikoss** [comment]
Да Вы правы все так.
Теперь работает норм.
Спасибо огромное.
