### ISSUE TITLE
Кнопка поделиться в товарах работает не всё

### ISSUE THREAD

**Issue by Andrikoss** [trydalcoholic/opencart-materialize#42]
Здравствуйте!
Отсутствие знаний программирования заставляет писать снова.

ocStore 2.3.0.2.3+materialize2,3,ч
Не работает поделиться в whatsapp и viber с мобильного устройства.
Открывается пустая страница с адресом 
whatsapp://send?text=...далее ссылка на товар
так же и в viber.
По идее на мобильном устройстве должно открывать соответствующее приложение.
В Default шаблоне это работает как я понимаю через https://www.addthis.com
Скажите пожалуйста как поправить ?
Заранее очень Вам признателен.

**Comment by trydalcoholic** [comment]
Здравствуйте!
Спасибо что рассказали об этом.
"Поделиться"для viber и whatsapp работают, очевидно, иначе, чем для других сервисов. На момент написания "поделиться", во время тестов срабатывало открытие как десктопных версий, так и мобильных приложений. Сейчас мобильное приложение действительно не реагирует. К сожалению, быстрого и верного исправления я не могу предложить.
Тем не менее, "поделится" я планировал вынести в отдельный модуль, после этой реализации, кнопки будут корректно работать на всех устройствах.

**Comment by Andrikoss** [comment]
Здравствуйте!
Как решение взял коды из яндекса и вставил между каждым Li 
Отдельно для каждой соцсети
Спасибо. Успехов Вам.

**Comment by trydalcoholic** [comment]
А что именно Вы взяли?
Для whatsapp, как я понял, был изменён share, Если заменить `whatsapp://send?text=` на `//api.whatsapp.com/send?text=` то происходит вызов приложения. С viber, похоже, всё сложнее.

**Comment by Andrikoss** [comment]
Дело в том что я не силен в разного рода коде.
Поверхностно имею представление о HTML и CSS 
Для себя решил проблему так ;
![screenshot_2](https://user-images.githubusercontent.com/34532476/34368685-c369dfbc-eac6-11e7-85b6-1fc2414ac569.png)
![screenshot_3](https://user-images.githubusercontent.com/34532476/34368686-c39c7d78-eac6-11e7-867d-f482902801eb.png)
![screenshot_4](https://user-images.githubusercontent.com/34532476/34368687-c3c9fe56-eac6-11e7-969b-ea4b6363c55d.png)
![screenshot_5](https://user-images.githubusercontent.com/34532476/34368688-c3f2127e-eac6-11e7-9064-8b53942b75cd.png)

Вроде все работает.

**Comment by trydalcoholic** [comment]
Понял, вы просто заменили на сервис Яндекса. В таком случае, Вам достаточно однократно вызвать скрипт Яндекса, т.е. `<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
<script src="//yastatic.net/share2/share.js"></script>` указать только один раз на странице, в остальном всё верно.

**Comment by trydalcoholic** [comment]
Правильные мысли только на свежую голову приходят. Всё в разы проще, у ссылок на viber и whatsapp надо было удалить `target="_blank"` 😒.
