### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by openscart** [trydalcoholic/opencart-materialize#43]
hello, thanks for this excellent theme. I made the installations and finally it's ok. No error occurs. 
But I can not add articles because the blog section does not appear in the admin section.
 Can you help me please?

**Comment by trydalcoholic** [comment]
Hello!
The blog is included through administrator rights.
System >> Users >> User groups >> Administrator >> Access Permission [Select All] and Modify Permission [Select All]

**Comment by openscart** [comment]
thank you ... it works. Merry Christmas!
