### ISSUE TITLE
Blog comment and blog breadcrumbs

### ISSUE THREAD

**Issue by aarontower** [trydalcoholic/opencart-materialize#44]
Hello, in latest 2.3, i find the blog comment can not be post successfully.
Besides there are some bugs about blog breadcrumbs.
attached my modification, if necessary, pls update next time .

	<file name="catalog/controller/blog/post.php">
		<operation error="skip" info="adjust blog post page breadcrumbs">
			<search><![CDATA[
				$this->load->model('blog/category');
			]]></search>
			<add position="before"><![CDATA[					
				$data['breadcrumbs'][] = array(
					'text' => $this->language->get('text_blog'),
					'href' => $this->url->link('blog/category')
				);
		]]></add>
		</operation>
	</file>

	<file name="catalog/controller/blog/search.php">
		<operation error="skip" info="adjust blog search page breadcrumbs">
			<search index="1"><![CDATA[
				$url = '';
			]]></search>
			<add position="before"><![CDATA[					
				$data['breadcrumbs'][] = array(
					'text' => $this->language->get('text_blog'),
					'href' => $this->url->link('blog/category')
				);
		]]></add>
		</operation>
		<operation error="skip" info="display tag in search result title">
			<search><![CDATA[
				$data['heading_title'] = $this->language->get('heading_title') .  ' - ' . $this->request->get['search'];
			]]></search>
			<add position="after"><![CDATA[					
				} elseif (isset($this->request->get['tag'])) {
				$data['heading_title'] = $this->language->get('heading_title') .  ' - ' . $this->language->get('heading_tag') . $this->request->get['tag'];
		]]></add>
		</operation>
	</file>

	<file name="catalog/language/en-gb/blog/search.php">
		<operation error="skip" info="adjust blog search page breadcrumbs">
			<search><![CDATA[
				$_['heading_title']		= 'Search';
			]]></search>
			<add position="before"><![CDATA[					
				$_['text_blog']						= 'Blog';
		]]></add>
		</operation>
	</file>

	<file name="catalog/language/en-gb/blog/post.php">
		<operation error="skip" info="adjust blog post page breadcrumbs">
			<search><![CDATA[
				$_['text_blog']						= 'Blog';
			]]></search>
			<add position="after"><![CDATA[					
				$_['text_search']						= 'Search';
		]]></add>
		</operation>
	</file>

**Comment by trydalcoholic** [comment]
Hello!
Your decision with bread crumbs is very useful, thanks for that!
I did not quite understand what kind of problems you have with the comments? At me all works trouble.

**Comment by aarontower** [comment]
Thanks for you comment and wish you a happy new year in advance! 

I test again in a new installed opencart 2.3
The problem is when i click continue to post a blog comment, nothing happen, no dialog for error or success, is there any setting requirement in back-end?

And i found another bug in search page of blog system, the blog search inputbox displays auto-complete search of products, and the product search inputbox displays the keyword. I think we should use different ID to separate blog search and product search.
![111](https://user-images.githubusercontent.com/33935789/34451169-2d8e8048-ed59-11e7-8b76-a7f1e0dbf4e3.jpg)

**Comment by trydalcoholic** [comment]
Hello!
I did a clean installation of OpenCart and the comments are not really sent.
The blog module requires a lot of processing, so all this will become part of the work on the module. After the module is improved, its functions will be expanded, and errors are corrected.
Thank you for reporting them!

**Comment by trydalcoholic** [comment]
Probably the problem with the addition of comments has been resolved. Check, please.
It is necessary to replace the corresponding files:

- /upload/catalog/controller/blog/post.php
- /upload/catalog/model/blog/comment.php

**Comment by aarontower** [comment]
Good job!  it's working now.

**Comment by openscart** [comment]
Hello,

the same problem occurs to me. I mention that the platform is Opencart 3.0.2.0. When I want to write a comment after entering the data and press the send button, nothing happens! You gave two files ... /upload/catalog/controller/blog/post.php
/upload/catalog/model/blog/comment.php
Where can I get them?
Regards,

**Comment by trydalcoholic** [comment]
@openscart here on github you can download separately files or the entire template of the latest version by clicking on the "Clone or download" button.
