### ISSUE TITLE
Automatic currency conversion

### ISSUE THREAD

**Issue by openscart** [trydalcoholic/opencart-materialize#45]
Hello!
When I enter the lei currency (my country's currency), it does not automatically update, by default 0.000000. The System / Settings / Location / Automatic Currency Update setting is YES.

**Comment by trydalcoholic** [comment]
Hello!
Materialize Template does not affect the work with currencies. The solution to this problem should be found in the OpenCart forums.
As far as I know, the old versions of OpenCart used yahoo services to automatically update the currency, now these services are closed. I'm sure there is a solution on the Internet for older versions of OpenCart.

**Comment by openscart** [comment]
Hello!
Thank you for replying ... I mention that I use OpenCart 3020 ..
Happy New Year!
Many happy returns of the day!

**Comment by openscart** [comment]
--
