### ISSUE TITLE
home page layout disorder and product page error

### ISSUE THREAD

**Issue by eric4048** [trydalcoholic/opencart-materialize#46]
oc version  is 2.3.0.2
http://120.77.182.155/opencart/   [home page]
http://120.77.182.155/opencart/index.php?route=product/product&product_id=43 [product page]

install step is no problem.

home page layout disorder image
![image](https://user-images.githubusercontent.com/7628273/34512537-1a3c4a14-f09e-11e7-9ca5-b1b5040f0cc5.png)

product page error image
![image](https://user-images.githubusercontent.com/7628273/34512544-27ff19ec-f09e-11e7-844a-946ac9040eb5.png)

**Comment by eric4048** [comment]
![image](https://user-images.githubusercontent.com/7628273/34513530-a66613d0-f0a3-11e7-8910-2fc81b4be844.png)
 
Solve Product Page Error Problem.

**Comment by aarontower** [comment]
哥们，这个模块管理里可以设置的

**Comment by eric4048** [comment]
恩，明白了，文档详细些就更好了，嘻嘻

**Comment by trydalcoholic** [comment]
Hello!
Thank you for reporting the error and searching for its solution!
In fact, the error is stored in the installation file materialize_theme.ocmod.xml, you need to change the line `$data['remainder'] = ''`; on `$data['type_remainder'] = ''`;
In its current form, the footer is designed to enter information about the store. In future updates, I will fix it.

**Comment by eric4048** [comment]
ok,get.
