### ISSUE TITLE
Undefined index: size_chart 

### ISSUE THREAD

**Issue by CodeNeedsCoffee** [trydalcoholic/opencart-materialize#47]
![image](https://user-images.githubusercontent.com/16927633/34626518-fbddec42-f22a-11e7-93b9-7ecba5ef5a82.png)

Undefined index: size_chart in /u01/www/www.peacefulacre.com/test/storage/modification/catalog/model/catalog/product.php

I get this as soon as I install the theme.
  
 Is there a way to remove the size chart?

**Comment by trydalcoholic** [comment]
Hello!
Please send a screenshot of your database.

**Comment by CodeNeedsCoffee** [comment]
Are you talking about SQL file that is uploaded? Or my actual database? I'm using MariaDB via SSH.
  
  Also, I uploaded the new git and more of the errors went away but now on product page this is all that loads.

![screenshot_1](https://user-images.githubusercontent.com/16927633/34671844-127a77b0-f44a-11e7-8f8b-6c422a74d36b.png)

**Comment by trydalcoholic** [comment]
I was referring to a screenshot of the list of tables in your database.
You have not installed the file sql_install_materialize_theme.ocmod.sql, the most likely reason is that you change the default database prefix is OpenCart.
