### ISSUE TITLE
search question:  no product

### ISSUE THREAD

**Issue by eric4048** [trydalcoholic/opencart-materialize#48]
link: http://aimo.free.ngrok.cc/index.php?route=product/search&category_id=27&sub_category=true
![image](https://user-images.githubusercontent.com/7628273/34757050-cb8964d0-f609-11e7-9170-2f0f4bd9d43e.png)

the search keywords is required?

**Comment by trydalcoholic** [comment]
This is the standard OpenCart search.
If there is no query to search, then there is nothing to show 🙂.
