### ISSUE TITLE
Консультация

### ISSUE THREAD

**Issue by Pozitivchik** [trydalcoholic/opencart-materialize#49]
Добрый день! Подскажите пожалуйста как:
1. Сделать надпись "Категории" больше и не нарушить структуру дизайна?
2. Края блоков сделать чётче и темнее? (Скриншот прилагаю).

![default](https://user-images.githubusercontent.com/33651511/34768454-856d7c9e-f603-11e7-852b-23b81862332f.png)

3. Правильно разорвать два блока, чтобы один переместился в левую сторону, а другой остался на правой стороне? (Скриншот прилагаю).

![11112](https://user-images.githubusercontent.com/33651511/34776648-4461d3cc-f620-11e7-85d1-f31d84c655e2.png)

**Comment by trydalcoholic** [comment]
Всё это большая тайна и храниться под большим секретом.
Могу только намекнуть, что в папках catalog/view/theme/materialize/template/common хранятся шаблоны шапки и меню, а шаблон карточки товаров храниться в catalog/view/theme/materialize/template/product/product.twig. А уж там вы можете задать любые css классы и настроить всё по вашему вкусу 🙂.

**Comment by Pozitivchik** [comment]
Спасибо). Я вот когда-то спрашивал Вас по поводу сокращения времени показа всплывающих уведомлений. Вы посоветовали найти  catalog/view/theme/materialize/js/script.js file and edit the line Materialize.toast('<span><i class="material-icons left">check</i>'+json['success']+'</span>',7000,'toast-success') и 7000 уменьшить до нужного варианта. Я это сделал и нашел такой скрипт в файле "produkt" везде заменил на 2500 но на время показа уведомлений это не повлияло. Возможно есть ещё варианты, поделитесь пожалуйста.
И ещё, я совершенно случайно в шаблоне наткнулся на код: https://materialize.myefforts.ru/clothing/footwear/new-balance-574-black"><img class="lazyload" src="data:image/gif;**base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw**==" data-src="https://materialize.myefforts.ru/image/cache/catalog/goods/clothing/sneakers/new-balance/574/black/new-balance-574-black-1-250x250.jpg"  успокойте пожалуйста, что он обозначает? И почему данные закодированы?

**Comment by trydalcoholic** [comment]
Верно, в файле product есть примерно такой же скрипт, отвечающий за добавления товара только на странице товара, скрипт из catalog/view/theme/materialize/js/script.js отвечает за все остальные случаи.
Единственный способ это изменение значения в этих скриптах. Проверьте ваши изменения в приватном (инкогнито) режиме.
**data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==** — закодированное однопиксельное изображение из оригинального скрипта [ленивой загрузки изображений](https://github.com/aFarkas/lazysizes). При загрузке страницы браузер получает несколько символов кода, позволяя начать рендер страницы значительно быстрее. После чего, вместо однопиксельного изображения скрипт начинает загружать реальные изображения.
