### ISSUE TITLE
(LOW PRIORITY) Russian language in the english template

### ISSUE THREAD

**Issue by 123Dragon** [trydalcoholic/opencart-materialize#5]
I know how to myself it directly, this is just an improvement down the road for people who cannot modify code:
Product detail page
![image](https://cloud.githubusercontent.com/assets/29109935/26686598/6f386634-46bb-11e7-8596-b4455ddf165f.png)

Hovering on the comparison button:
```
<a id="compare-btn" href="http://www.racingking.ca/open/index.php?route=product/compare" class="btn-floating btn-large waves-effect waves-light blue z-depth-4 scale-transition pulse " title="Список сравнения" rel="nofollow">
		<i class="material-icons">compare_arrows</i>
		<small id="compare-total" class="light-blue darken-2 btn-floating z-depth-1 pulse">3</small>
	</a>
```

There is also the hover on the SAVE and STAY button on the admin side, but it doesn't' bother me at all.
You have done an amazing job with the template, I am extremely grateful and I have happy to help debug.

**Comment by 123Dragon** [comment]
English translation in header.tpl line 268 to translate Список сравнения
`<a id="compare-btn" href="<?php echo $compare; ?>" class="btn-floating btn-large waves-effect waves-light blue z-depth-4 scale-transition pulse <?php if ($text_compare==0) {echo 'scale-out';} ?>" title="Compare products" rel="nofollow">`

**Comment by trydalcoholic** [comment]
Thanks for the help 😏.

**Comment by 123Dragon** [comment]
Login.tpl and chechout/login.tpl
`<label for="input-email" data-error="Ошибка при вводе e-mail" data-success="E-mail введён верно"><?php echo $entry_email; ?></label>`

to be changed with:

` <label for="input-email" data-error="Wrong e-mail" data-success="E-mail Valid"><?php echo $entry_email; ?></label>`

**Comment by 123Dragon** [comment]
common/cart.tpl
Line 66
`<p>Давай помогу тебе потратить деньги :)</p>`

To be replaced with:
`<p>Let me help you spend some money :)</p>`

**Comment by trydalcoholic** [comment]
Thank you for helping with the translation!
And also thanks for your feedback on the marketplace 😊.
All your comments will be taken into account in one of the future updates.
