### ISSUE TITLE
Forgot Password Waring

### ISSUE THREAD

**Issue by eric4048** [trydalcoholic/opencart-materialize#52]
Click the link into the page that reset the password in the mail ,have waring .

![20180122112913](https://user-images.githubusercontent.com/7628273/35204219-a6f2717c-ff67-11e7-979d-d0e70ed72d50.png)

**Comment by trydalcoholic** [comment]
Hello!
Thank you reported this bug!
Here's a quick version of the fix. 
Locate and edit the file catalog/view/theme/materialize/template/account/reset.tpl (.twig). Replace the line `<?php echo $text_email; ?>` to `<?php echo $text_password; ?>`. For OpenCart 3 `{{ text_email }}` to `{{ text_password }}`

**Comment by eric4048** [comment]
thx ,perfect.
