### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by AlexanderOrNot** [trydalcoholic/opencart-materialize#53]
Привет
Чтобы не заморачиваться, отпишу тут:
opencart_3.x/upload/catalog/view/theme/materialize/template/account/order_info.twig
строка 72 - Пропустил if перед invoice_no
opencart_3.x/upload/catalog/view/theme/materialize/template/common/maintenance.twig
строка 2 - Начал с  % endspaceless %

**Comment by trydalcoholic** [comment]
Здравствуйте!
Спасибо что написали об этом!

**Comment by moshkinura** [comment]
https://github.com/trydalcoholic/opencart-materialize/issues/58
Тут я тоже "ошибку" нащел
