### ISSUE TITLE
Searchbox разметка

### ISSUE THREAD

**Issue by AlexanderOrNot** [trydalcoholic/opencart-materialize#54]
Разметку Searchbox которая "@context": "http://schema.org","@type": WebSite" и т.д. нужно вставлять только на главной странице. (https://developers.google.com/search/docs/data-types/sitelinks-searchbox)
Так что наверное лучше её вкрутить в home

**Comment by trydalcoholic** [comment]
Здравствуйте!
Действительно, согласно документации в шаблоне, получается, есть ошибка с этой разметкой.
Спасибо что сообщили об этом!
