### ISSUE TITLE
商品详情页关联商品的优惠比没定义报错

### ISSUE THREAD

**Issue by eric4048** [trydalcoholic/opencart-materialize#55]
![image](https://user-images.githubusercontent.com/7628273/35715564-3bf2e1ae-080e-11e8-8d8e-095ee4e4f9d2.png)

https://www.markurlife.com/index.php?route=product/product&product_id=50

**Comment by trydalcoholic** [comment]
Please send this file or its contents: system/storage/modification/catalog/controller/product/product.php

**Comment by eric4048** [comment]
![image](https://user-images.githubusercontent.com/7628273/35736198-1db52e28-0862-11e8-8176-541486224264.png)

应该在D:\WWW\opencart\install\ocmod\materialize_theme.ocmod.xml 的2721行后面添加图片的内容。
![image](https://user-images.githubusercontent.com/7628273/35736302-782df6be-0862-11e8-815e-d8007b08a7fc.png)
![image](https://user-images.githubusercontent.com/7628273/35736313-84ec07c4-0862-11e8-8c6b-69cab7d04713.png)
我自已手动添加了，也可以在xml添加。

**Comment by trydalcoholic** [comment]
I still did not understand what exactly you meant and what you suggested for the solution.
Look at the recommended products on the [demo site](https://materialize.myefforts.ru/protein/whey/nanox-protilox-2-kg).
Everything is correctly displayed, so I do not quite understand the reason for the error on your site.

**Comment by AlexanderOrNot** [comment]
eric4048 you've doubled it
materialize_theme.ocmod.xml:2656 `
	<file path="catalog/controller/product/{category,manufacturer,product,search,special}*.php">
		<operation error="log">
			<search><![CDATA[$special = $this->currency->format($this->tax->calculate($result['special'], $result['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);]]></search>
			<add position="after"><![CDATA[$percent_discount = round(100-($result['special']/($result['price']/100)));]]></add>
		</operation>`
Check your ocmod.log for errors.
