### ISSUE TITLE
new customer registration form

### ISSUE THREAD

**Issue by kiriltsev704** [trydalcoholic/opencart-materialize#56]
Hello!
During ordering, in the registration form when I tap continue button without filling any fields there is appearing only one warning - to check security policy, but no warnings for the name, address, password e.t.c. 
![image](https://user-images.githubusercontent.com/35704262/35772229-384a9d60-094b-11e8-92f5-4c344ad42de4.png)

**Comment by trydalcoholic** [comment]
Will be fixed.
Thank you for reporting this!
