### ISSUE TITLE
Blog on fresh OC 3.0.2.0 not showing in Admin

### ISSUE THREAD

**Issue by AverageJ0E** [trydalcoholic/opencart-materialize#57]
Just did a fresh Opencart 3.0.2.0 install and then did a fresh install of the master. I don't see the Blog anywhere in the Admin Menu. I have no errors in the error log. I do see it in the Extensions and have enabled it and the Templates one too. I have also enabled the Call Back and it works fine. Just the Blog has no place o add and entry or anything in the Admin. Am I missing something?

Other than not figuring out the Blog, it's a very nice theme!

Thank you!

**Comment by trydalcoholic** [comment]
Duplicate of #43

**Comment by AverageJ0E** [comment]
Perfect! 

Thank You!
