### ISSUE TITLE
Blog problem

### ISSUE THREAD

**Issue by Eddiecz** [trydalcoholic/opencart-materialize#59]
Hi, I just did a fresh Opencart 3.0.2.0 install, template install, and I have problem with blog. In Extension setting is Search posts, List of categories and Recent Posts enabled, but not showing on Blog page.
Administrator rights enabled too.

See: https://mriha.cz/subdom/open/index.php?route=blog/category

Thank for help.

**Comment by trydalcoholic** [comment]
Duplicate of #43

**Comment by Eddiecz** [comment]
I have permission enabled, but still not working. Blog page is showinng, but not Search posts, List of categories and Recent Posts.
![permission](https://user-images.githubusercontent.com/4080487/36193861-c5bc28ca-1167-11e8-9245-a80b6a8aca4f.PNG)

**Comment by trydalcoholic** [comment]
I apologize, I inattentively read the question!
You must add a layout for the blog.
To do this, go to Desgin >> Layouts.
Click the "Add New" button.
For example, "Blog Categories". Route specify: "`blog/category`". Add the modules to the columns you need.
By analogy with this, do the same for the pages of the post and search, indicating the route as `blog/post` and `blog/search`

**Comment by Eddiecz** [comment]
Thank you.
