### ISSUE TITLE
IMPROVEMENT: Image next to the radio button option missing

### ISSUE THREAD

**Issue by 123Dragon** [trydalcoholic/opencart-materialize#6]
**Stock template:**
![image](https://cloud.githubusercontent.com/assets/29109935/26701111/d5faeac2-46ed-11e7-85eb-153929102fba.png)

**Materialize template:** (The images are missing next to the tool)
![image](https://cloud.githubusercontent.com/assets/29109935/26701159/0450d44a-46ee-11e7-80b2-05f123c5a9aa.png)

I am am only documenting my findings.

**Comment by 123Dragon** [comment]
Solved it. Correction in product.tpl line 234
`<img src="<?php echo $option_value['image']; ?>" data-src="<?php echo $option_value['image']; ?>" alt="<?php echo $option_value['name'] . ($option_value['price'] ? ' ' . $option_value['price_prefix'] . $option_value['price'] : ''); ?>" class="responsive-img">`

It works now: If there is no image, I put a blank pixel instead of an image (I didn't feel like coding it)
![image](https://cloud.githubusercontent.com/assets/29109935/26727273/30a3dc8c-4774-11e7-8a2f-2afee3302e8f.png)

**Comment by trydalcoholic** [comment]
> Solved it. Correction in product.tpl line 234

Maybe I misunderstood you)
For the options with and without the image to be displayed with the same indentation, you do not need to encode already. The paradox is that for an option without an image, you need to specify an empty transparent image, for example:
- In Photoshop create a transparent image size 1x1 pixel and save it in .png format (save with transparency);
- upload the resulting image to the folder OpenCart;
- for the corresponding options specify a transparent image.
As I understand it, this is what you did 😉.
