### ISSUE TITLE
shopping cart / phone mask / empty cart message

### ISSUE THREAD

**Issue by openscart** [trydalcoholic/opencart-materialize#60]
Hi,
I have a great prayer, and I'm sure they are somewhat more skilled than me. That's why I'm asking for help.
1. the shopping cart (the one at the bottom of the page) appears only when a product is inserted into the cart.

2. how do I delete the phone's mask (country prefix) so that it does not appear anymore.

3. How do I replace the message: Do I help you to spend your money :) in the empty basket?

Thank you,

**Comment by trydalcoholic** [comment]
To delete a mask, you need to manually find the appropriate layouts and edit the code, similar to: `<input type="tel" name="telephone" value="{{ telephone }}" id="input-telephone" class="validate" placeholder="+7_(___)___-____" data-inputmask="'alias':'phone'">`
Change it to this: `<input type="tel" name="telephone" value="{{ telephone }}" id="input-telephone" class="validate">`
This template matches the file: `catalog/view/theme/materialize/template/account/register.twig`
The cart template in OpenCart is edited here: catalog/view/theme/materialize/template/common/cart.twig

**Comment by openscart** [comment]
Thank you very much...

**Comment by DmitryUA13** [comment]
ПРивет) Нужна подсказка. Я установил шаблон на Opencart 3.0.0 и после установки слетети CSS. Как можно устранить этот вопрос. Я новичек, может чего и не понимаю

**Comment by trydalcoholic** [comment]
Здравствуйте @DmitryUA13!
Следуйте [инструкции](https://github.com/trydalcoholic/opencart-materialize/blob/master/Documentation_rus.pdf), Вы не выполнили обязательный пункт для OpenCart со страницы 4.
