### ISSUE TITLE
Errors from header.tpl

### ISSUE THREAD

**Issue by cernega** [trydalcoholic/opencart-materialize#61]
Can't resolve all this errors can you please give me a hiny?
<img width="1003" alt="screen shot 2018-02-15 at 18 49 50" src="https://user-images.githubusercontent.com/36512872/36269136-0b3fac40-1281-11e8-8dd5-0531625a8988.png">

**Comment by trydalcoholic** [comment]
Hello!
Please read the installation instructions: https://github.com/trydalcoholic/opencart-materialize/blob/master/Documentation_eng.pdf
Pay attention to page 4

**Comment by cernega** [comment]
I've done it again and now it's ok. Thanks!
