### ISSUE TITLE
Support Opencart 3.0.3.0b

### ISSUE THREAD

**Issue by Eddiecz** [trydalcoholic/opencart-materialize#62]
Hi,
please, do you plan to support version 3.0.3.0b? Older versions are unusable, because many bugs. I'm testing version 3.0.3.0b here:
https://open.rfid-shop.cz  it seems be good and usable for me. But with your template v 0.80 from here: https://github.com/trydalcoholic/opencart-materialize/tree/master/opencart_3.x and testing site here: https://zentest.rfid-shop.cz/ here are some issues. Language switching stops working, and also Blog link not working.
Thank you for help and support.

**Comment by trydalcoholic** [comment]
Hello!
If in brief to answer your question, then yes, in the future, of course, the latest version of OpenCart will be supported, but only when it is released. You can follow the release here: https://github.com/opencart/opencart/releases
The version of the 0.80 template is in a different folder and is not yet ready for release. As well as the version of OpenCart 3.0.3.0b is also not a release from the developers and will constantly change until it comes out in the release. Therefore, it is technically difficult to maintain this version.

**Comment by Eddiecz** [comment]
As I wrote, previous versions Opencart 3.x are buggy and unusable. Version 3.0.3.0b is released here: https://www.opencart.com/index.php?route=cms/download/history

**Comment by trydalcoholic** [comment]
I understand. Previously, this version was called 3.0.2.1b
Developers will change this index until this version is released and will be named, something like OpenCart 3.1
Note the developer notes for these releases: "3.0.3.0 (Beta) Non production Beta Do not use on a live web site."

**Comment by Eddiecz** [comment]
OK, I understand, but last version is better then olders :-)
No problem, I'll wait for the official version, thank you.
