### ISSUE TITLE
Warning message pops on top

### ISSUE THREAD

**Issue by Puffz** [trydalcoholic/opencart-materialize#63]
Hello! I'm following the steps in the documentation, but at the end I always receive this warning message on top of the screen. OpenCart version 3.0.2

```
getimagesize(http://opencarttu.dx.am/image/catalog/cart.png): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in
/srv/disk5/2612752/www/opencarttu.dx.am/system/storage/modification/catalog/controller/common/header.php
on line
85
```

I've located line 85 but can't fix it:

```
if (is_file(DIR_IMAGE . $this->config->get('config_icon'))) {
			
			$this->load->model('tool/image');

			$file = ($server . 'image/' . $this->config->get('config_icon'));
			$info = getimagesize($file);
			$icon_type = isset($info['mime']) ? $info['mime'] : '';
```

**Comment by trydalcoholic** [comment]
Hello!
Unfortunately I did not encounter such a problem and it is difficult for me to determine the exact cause. If you have the opportunity, please provide access to your FTP to me on the mail: gatalsky94@yandex.ru
