### ISSUE TITLE
[Order info] Fatal error: Uncaught exception 'Twig_Error_Syntax'

### ISSUE THREAD

**Issue by ikourfaln** [trydalcoholic/opencart-materialize#65]
## Describe your actions ##
I get a Twig error when I try to view detail of my order

## Expected behavior ##
Order detail page

## Possible solution of the problem ##
It's a twig syntax error, so the issue is clear

## Indicate if possible ##
* Chrome (Latest)
* Version of the OpenCart: 3.0.2.0
### Exeption message ###
`
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected "invoice_no" tag (expecting closing tag for the "spaceless" tag defined near line 3) in "materialize/template/account/order_info.twig" at line 75.' in /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/Parser.php:172 Stack trace: #0 /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/TokenParser/Spaceless.php(32): Twig_Parser->subparse(Array, true) #1 /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/Parser.php(187): Twig_TokenParser_Spaceless->parse(Object(Twig_Token)) #2 /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/Parser.php(100): Twig_Parser->subparse(NULL, false) #3 /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/Environment.php(619): Twig_Parser->parse(Object(Twig_TokenStream)) #4 /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/Environment.php(671): Twig_Environment->parse(Object(Twig_TokenStream)) #5 /home/azurestag2004/public_html/e in /home/azurestag2004/public_html/eo-oc/system/library/template/Twig/Parser.php on line 172
`

**Comment by trydalcoholic** [comment]
Hello!
This error has already been mentioned #53 and has been fixed in the new version.
