### ISSUE TITLE
category_id > blog_category_id

### ISSUE THREAD

**Issue by rashidgizzatov** [trydalcoholic/opencart-materialize#66]
Добрый день!
В файле opencart_3.x\install\sql\sql_install_materialize_theme.ocmod.sql в таблицах ошибка:
oc_blog_category
oc_blog_category_description
oc_blog_category_path
oc_blog_category_to_layout
oc_blog_category_to_store
В модуле блога не может найти колонку blog_category_id , после исправления всё заработало

**Comment by trydalcoholic** [comment]
Здравствуйте!
Спасибо, что сообщили об этом!
Честно говоря не сразу понял в чём именно ошибка. Я так понимаю Вы имеете в виду проблему с SEO URL? Так как база данных и запись в базу данных происходит верно, а вот как раз в seo url, как я увидел, есть несоответствие.
Тем не менее, в новой версии шаблона подобных проблем нет.
