### ISSUE TITLE
Как убрать страницу "Ваша корзина"?

### ISSUE THREAD

**Issue by Pozitivchik** [trydalcoholic/opencart-materialize#67]
Добрый день.
Подскажите пожалуйста как сделать, чтобы нажимая на круглую кнопку корзины сразу открывалась страница "Корзина покупок"?
 И какой модуль подойдет к этому шаблону для упрощения оформления заказа через корзину?

**Comment by trydalcoholic** [comment]
Здравствуйте!
Просто поменяйте ссылку.
К сожалению, я вынужден закрывать подобные вопросы. Здесь нет проблем с некорректной работой шаблона.
