### ISSUE TITLE
Product images from a different domain?

### ISSUE THREAD

**Issue by cernega** [trydalcoholic/opencart-materialize#68]
It used to work on 1.5.6.4 but now it doesn't...
To be more specific i'm talking about when i'm importing products with import/export tool in the excel on image_name section to add the route to the suppliers image: myshop.com serves images from suppliersshop.com/images/etcetera

**Comment by trydalcoholic** [comment]
Hello!
Unfortunately, I have to close this issue, because the template does not import images. Accordingly, there are no problems with incorrect operation of the template.

**Comment by cernega** [comment]
I've done it. It's on opencart forum. If I'll find the link i'll post it here. Basically in import/export excel file on image column you paste the link from suppliers image. mywebsite.com serves images from supplierswebsite.com *wink*
