### ISSUE TITLE
Изображений подкатегорий

### ISSUE THREAD

**Issue by moshkinura** [trydalcoholic/opencart-materialize#69]
Здравствуйте, извините не нащел куда вам можно написать.
Такой вопрос, как сделать так, что-бы на странице категории, изображения подкатегории выводились не 32на32 а допустим 100на100.
В " Модули/Расширении => Темы => Materialize Template ", такого пункта не нащел.
Пробовал и в файле " catalog/controller/product/category.php " всё что с изображениями связанно менять.(по гайдам из интернета), не помогло!
Буду очень признателен, если поможете!

P.S Также этот пост можно считать за идею в добавлении настроек шаблона, размеров изображений категорий/подкатегорий.

**Comment by AlexanderOrNot** [comment]
Модули/Расширения => Темы => Materialize Template => Вкладка "Изображения" => https://i.gyazo.com/d97eedf4e0358b5e15f2b3a4f53028f1.png

**Comment by moshkinura** [comment]
@AlexOrlovets Я видимо не так объяснил) Ладно сейчас распишу.
Когда я выбираю изображение категории, и вызываю ее через **{{ category.thumb }}**, в файле **product/category.twig** на странице выводится изображение: 

> SITE.RU/image/cache/catalog/demo/apple_cinema_30-32x32.jpg

т.е она ее прогоняет через кэш, использует маленькое изображение. Как обойти этот кэш и использовать изображение оригинал? 

> SITE.RU/image/catalog/demo/apple_cinema_30.jpg

И кстати я не уверен конечно, но ваш вариант он меняет на странице размер(изменяет значение width и height изображения), точно сказать не могу, т.к шаблон уже переделан.

**Comment by trydalcoholic** [comment]
Здравствуйте!
Размер изображений вы можете изменить в установочном .xml файле, найдите строку: `$image = $this->model_tool_image->resize($result['image'], 32, 32);`, измените цифры 32 на необходимый вам размер. Затем переустановите этот файл и обновите кэш модификаторов.
В текущем виде добавлять это в настройки не имеет смысла, так как подкатегории реализованы через chips и будут иметь изображения размером 32 на 32.
