### ISSUE TITLE
Undefined index: add_cart

### ISSUE THREAD

**Issue by mosleim** [trydalcoholic/opencart-materialize#7]
i have install materialize in my store. but, i get some error. like this:

`Notice: Undefined index: add_cart in /var/www/-oyur.com/upload/system/storage/modification/catalog/model/catalog/product.php on line 56`

this error is triggered from this route:

`/index.php?route=product/product&product_id=43`

why it's happen? and how to solve?

**Comment by trydalcoholic** [comment]
Hello!
Honestly, I do not know what it can be.
Obviously, the error is related to the query to the database.
Did you follow the installation instructions (pay special attention to the second step)?
Did you install other modules?

**Comment by mosleim** [comment]
yes, i have import the sql file.
my environment is:

- PHP7
- Ubuntu 16.0.4
- mysql  Ver 14.14 Distrib 5.7.12
- Opencart 2.3.0.2 fresh install. 
- No other module installed

error is triggered by all dummy product detil. 

i have reinstall my Openchart, and import sql file whithout install the theme. just import sql file. and no error triggered.

**Comment by trydalcoholic** [comment]
Please check your database, after importing the installation file, there should appear two tables: "oc_product_customtab" and "oc_product_customtab_description", and also check the table "oc_product", there should appear a new line "add_cart".
I suspect that nothing was written into the "oc_product" table 😓...

**Comment by pinecreativelabs** [comment]
I have also gotten this same issue! Followed the instructions EXACTLY, and when I tried importing in PHPMyAdmin, it threw an error, so the database import clearly has a major issue.

**Comment by mosleim** [comment]
sometime, it threw an error like this:

`ERROR 1067 (42000) at line 1: Invalid default value for 'date_available'`

when importing to mydatabase.

**Comment by trydalcoholic** [comment]
Thank you for reporting errors. Unfortunately, I can not personally face the problem.
I would be grateful if you check another installation file. Here is more simplified import into the database. In my case, again there is no error when importing 😔.

**[materialize_sql.zip](https://github.com/trydalcoholic/opencart-materialize/files/1072940/materialize_sql.zip)**

![image](https://user-images.githubusercontent.com/20430159/27105186-581d22e2-5097-11e7-835c-acbc18d2f785.png)

Regarding ERROR 1067, it is not related to the topic of Materialize. As you can see, the `date_available`field is not used in the installation SQL file. Anyway, the error informs that in the table `oc_product`, the `date_available` field does not have a default value, but it should be 0000-00-00. I do not know Why the default value could be lost..

P.S. SQL installation file is calculated that the database uses the prefix `oc_`. In any case, I will clarify.

**Comment by mosleim** [comment]
i have import succesfully . before importing the sql-file:
` set @sql_mode_bu = @@sql_mode; set @@sql_mode='';`
and then, after import i release the sql_mode variable `set @@sql_mode = @sql_mode_bu;`

reference to [this](https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at).

it happen in mysql new versions, no issue for oldest mysql. and i think i'ts not issue for this module, this happen for spesific configuration.

**Comment by trydalcoholic** [comment]
Perhaps it really depends on the configuration of the database.
I use the latest versions on test sites, but I have not encountered problems... ¯\_(ツ)_/¯

**Comment by 123Dragon** [comment]
I also have the template working without any problem on opencart Version 2.3.0.2. I used phpMyAdmin to run the sql script and it worked without a glitch.

**Comment by pinecreativelabs** [comment]
When I try the import, I am getting an error telling me that the "oc_product" table does not exist.

I am trying to do this on a brand new fresh install, where I haven't done anything at all (no other extensions, themes, etc.). 

Looking at the list of tables, I do not see oc_product anywhere at all. 

How do I fix this?

**Comment by mosleim** [comment]
@pinecreativelabs maybe your prefix is not "oc_"

**Comment by pinecreativelabs** [comment]
That's what I did wrong! I'm a newbie to OpenCart, so I left out the prefix upon installation.

Did a fresh install, and everything works just fine, including the theme install!
