### ISSUE TITLE
Не корректное отображение картинок в слайдере и карточке товара

### ISSUE THREAD

**Issue by dplays** [trydalcoholic/opencart-materialize#70]
Здравствуйте. Спасибо за проделанную Вами работу по шаблону Materialize.
У меня иногда возникает проблема при открытии главной страницы сайта и карточки товара - картинки слайдера, товара и производителей отображаются в столбик, при нескольких переходах со страницы на страницу всё нормализуется.
испытуемые: ocShop 2.3, русская сборка opencart 2.3
браузеры Firefox development edition 60.0b5(x64), K-Meleon 76 Pro , Smiljet 18.0.1.0 (на основе Chromium 64.0.3282.119), а также разные браузеры на Samsung N9005 (везде периодически возникает этот эффект)
устанавливал и на бесплатный и платный хостинг (баг остаётся)
на локальном сервере багов не было.
Подскажите в чём может быть причина.
Ещё раз спасибо за Вашу работу.
![bug](https://user-images.githubusercontent.com/37654483/37761083-b4d0c196-2dc9-11e8-8af6-e46576f7921e.jpg)

**Comment by trydalcoholic** [comment]
Здравствуйте!
Мне не удаётся воссоздать эту проблему.
Очевидно только то, что у вас либо прекращается работа javascript полностью, либо перестаёт работать библиотека слайдеров — slickjs.
Попробуйте изменить способ инициализации скрипта, найдите в соответствующих шаблонах подобную строку
`$('.slick-carousel').not('.slick-initialized').slick({`
и измените на
`$('.slick-carousel').slick({`
