### ISSUE TITLE
(footer.twig) materialize template not change

### ISSUE THREAD

**Issue by smarta1980** [trydalcoholic/opencart-materialize#72]
Hi, dear

catalog/view/theme/materialize/template/common/footer.twig

I change materialize template to another name and also changed the link to other link and save the footer file

but there are no any change the materialize temple is same and same link no any change

could you please check what is the problem?

thanks

**Comment by trydalcoholic** [comment]
Hello!
There is no problem with the template! In OpenCart 3, by default, developer mode is disabled and templates are cached.
On the main administrator panel in the upper right corner, click on the gear. Disable the theme cache and click the "Refresh" button.

![screenshot-2018-3-28 dashboard](https://user-images.githubusercontent.com/20430159/38007388-de20912a-3251-11e8-9fa6-77cfdd370985.png)
