### ISSUE TITLE
Убрать точки навигации

### ISSUE THREAD

**Issue by Andrikoss** [trydalcoholic/opencart-materialize#73]
Здравствуйте!
Скажите пожалуйста, как убрать ( удалить или отключить ) эти точки навигации на карусели
Скрин прилагаю
Сам не нашел, так как не силен в коде.
Заранее признателен.
С уважением Андрей!
![screenshot_1](https://user-images.githubusercontent.com/34532476/38245103-8754fd1a-3745-11e8-84e3-7b5b1fe6ca78.jpg)

**Comment by trydalcoholic** [comment]
Здравствуйте!
Этот вопрос не связан с некорректной работой шаблона, я вынужден закрыть вопрос.
