### ISSUE TITLE
MATERIALIZE "ОБРАТНЫЙ ЗВОНОК"

### ISSUE THREAD

**Issue by astengrau** [trydalcoholic/opencart-materialize#74]
Добрый день.
Скажите пожалуйста есть ли возможность что-бы при быстром заказе приходило уведомление на почту? А то не сильно удобно постоянно заходить в админку и смотреть не пришел ли новый заказ.
Спасибо

**Comment by trydalcoholic** [comment]
Здравствуйте!
И Быстрый заказ и Обратный звонок присылают уведомления на почту, которую вы указываете в настройках магазина.
Если вы не получаете письма, пожалуйста, проверьте папку спам и настройки почтового сервера.
