### ISSUE TITLE
Save changes to the template and settings

### ISSUE THREAD

**Issue by jun-dev** [trydalcoholic/opencart-materialize#75]
Hello. If I install an update of your OCMOD theme, will all my changes disappear? If so, how best to keep the current state and add fixes?

**Comment by trydalcoholic** [comment]
Hello!
If you did not make any changes to the template code and if you are upgrading to the version of the same main index, for example, from version 0.80 to 0.80.1, your changes will not disappear.
In other cases, it is better to make a backup of the site and deploy it, for example, on a local server. Then manually change the settings to yours, checking what was in the old version.

**Comment by jun-dev** [comment]
Thanks for the quick response.
I made changes through the built-in editor and in CSS, as far as I understood, everything will disappear during the update.
Okay, so I will try and update zabekaplyus through OCMOD.
