### ISSUE TITLE
After the upgrade of OpenCart from 3.0.2.0 to version 3.1.0.0 beta, the styles on the page (CSS) are no longer loaded. 

### ISSUE THREAD

**Issue by jun-dev** [trydalcoholic/opencart-materialize#76]
Hello.
After the upgrade of OpenCart from 3.0.2.0 to version 3.1.0.0 beta, the styles on the page (CSS) are no longer loaded. Also in the settings of the module it is impossible to select colors and in general it hardly works.

I already sent a message to the developers of the Opencards, but can you advise something, a temporary fix?

<details>
 <summary> For Russian speak users / Сообщение на Русском языке (SPOILER)</summary>
Здравствуйте.<br>
После обновления Опенкарт с 3.0.2.0 до версии 3.1.0.0 бета, перестали загружаться стили на странице (CSS ). Также в настройках модуля невозможно выбрать цвета да и вообще он едва работает.<br><br>

Я уже направил сообщение разработчикам Опенкарт однако может Вы что-нибудь посоветуете, временный фикс?
</details>

**Comment by trydalcoholic** [comment]
Please see the technical information on the template: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=30715
The maximum supported version of OpenCart 3.0.2.0

**Comment by jun-dev** [comment]
Thank u for the fast response. Good day.
