### ISSUE TITLE
Ошибка 500 сервера, после обновления

### ISSUE THREAD

**Issue by moshkinura** [trydalcoholic/opencart-materialize#80]
Здравствуйте. Решил обновить "ваше исскуство", для дополнительных плюшек.
Но после обновления, идет 500 ошибка сервера.
ERRORLOG:

> PHP Fatal error:  Uncaught Exception: Error: Table 'opencart.oc_materialize_social_networks' doesn't exist<br />Error No: 1146<br />SELECT * FROM oc_materialize_social_networks ORDER BY sort_order ASC in /home/s/opencart/opencart/public_html/system/library/db/mysqli.php:40\nStack trace:\n#0 /home/s/opencart/opencart/public_html/system/library/db.php(45): DB\\MySQLi->query('SELECT * FROM o...')\n#1 /home/s/opencart/opencart/public_html/admin/model/extension/materialize/materialize.php(593): DB->query('SELECT * FROM o...')\n#2 /home/s/opencart/opencart/storage/modification/system/engine/loader.php(248): ModelExtensionMaterializeMaterialize->getSocialIcons()\n#3 /home/s/opencart/opencart/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array)\n#4 /home/s/opencart/opencart/public_html/admin/controller/extension/theme/materialize.php(649): Proxy->__call('getSocialIcons', Array)\n#5 /home/s/opencart/opencart/storage/modification/system/engine/action.php(79): ControllerExtensionThemeMaterialize->index()\n#6 /home/s in /home/s/opencart/opencart/public_html/system/library/db/mysqli.php on line 40

Адаптируйте, пожалуйста, что-бы можно было без проблем обновляться с прошлой версии.
И если это ваша ошибка, исправьте ее пожалуйста.

**Comment by moshkinura** [comment]
Ошибку выше, сначало подумал что исправил(скорее всего обновлением файлов).
Но теперь новая ошибка. (Исправил комментированием 158 строки ");" )

> PHP Parse error:  syntax error, unexpected ')' in /home/s/opencart/opencart/storage/modification/catalog/controller/product/category.php on line 158

**Comment by trydalcoholic** [comment]
Здравствуйте!
В текущем виде, в шаблоне не предусмотрено безопасное обновление. Только со следующей версии будет уложена структура всех компонентов и как следствие, будет продумана возможность безопасного обновления.
Тем не менее, обновление смежных версий не вызывает никаких ошибок, именно по такому принципу обновляется демо сайт.
Конкретно в вашем случае, ошибку надо искать в 158 строке файла: `/home/s/opencart/opencart/storage/modification/catalog/controller/product/category.php`

**Comment by moshkinura** [comment]
> Конкретно в вашем случае, ошибку надо искать в 158 строке файла: /home/s/opencart/opencart/storage/modification/catalog/controller/product/category.php
Это я сделал. просто закоментировал 158 строку.

Но почему у меня матерится на то что не может запрос сделать в БД 
SELECT * FROM oc_materialize_social_networks ORDER BY sort_order ASC in....
Я такую БД даже не нащел...
Даже где у вас отдельный файл, что-бы добавить строки в БД...

**Comment by trydalcoholic** [comment]
Таблицы автоматически устанавливаются при установке темы/модулей.
При попытке обновиться, в расширениях необходимо удалять тему/модули, затем заново установить, что приведёт к потери ранее заполненной информации, что как следствие, требует какого-либо бэкапа информации.
Либо вручную отслеживать изменения в последней версии и также вручную восполнять новые изменения.

**Comment by moshkinura** [comment]
@trydalcoholic Так я полностью удалял модуль/тему, очищал БД ибо там нечего прям такого важного нету. 
Потом как бы, заного ставил...
Пожалуйста, предоставьте дамп БД, которые используются в вашем модуле.
Желательно: oc_materialize_social_networks

**Comment by trydalcoholic** [comment]
```
CREATE TABLE IF NOT EXISTS `" . DB_PREFIX . "materialize_social_networks` (
	`icon_id` int(11) NOT NULL AUTO_INCREMENT,
	`language_id` int(11) NOT NULL,
	`title` varchar(128) DEFAULT NULL,
	`link` varchar(255) DEFAULT NULL,
	`icon` varchar(255) DEFAULT NULL,
	`sort_order` int(3) NOT NULL,
	PRIMARY KEY (`icon_id`)
) ENGINE=MyISAM;
```

Выполните SQL запрос в phpMyAdmin, вместо `" . DB_PREFIX . "` подставив префикс Вашей бд, например. `oc_`
