### ISSUE TITLE
i have installed opencart-materialize theme but it's showing blank page.im using op(2.3.0.2).  This happened when I set the multi seller feature. The default theme works fine in this situation. Any help would be appreciated.

### ISSUE THREAD

**Issue by nizamudeen003** [trydalcoholic/opencart-materialize#83]
> Make sure that the problem is not related to the operation of the OpenCart and its settings. If the problem is related to the standard OpenCart functionality, make sure that there is no problem in the standard template and only appears in the Materialize Template.
> **If your question is not related to the problem in the work of the template or its modules, or you do not offer an idea for improving the work of the template, your question will be closed.**

## Describe your actions ##
If possible, add a link to your problem. Specify the steps to reproduce the problem.

## Expected behavior ##
What do you think should actually happen instead of a mistake?

## Possible solution of the problem ##
If you are proposing a solution, please describe it. If you just report a problem, you can skip this paragraph.

## Indicate if possible ##
* The name of your browser and its version;
* Version of the OpenCart and a translation for your language (if any);
* Screenshots.

**Comment by trydalcoholic** [comment]
Hello!
Please write, what exactly did you do?
I should note that the version for OpenCart 2.3 is in the archive and does not develop.
