### ISSUE TITLE
Свой цвет

### ISSUE THREAD

**Issue by iron-zorin** [trydalcoholic/opencart-materialize#87]
Возможно ли добавить в палитру свой цвет?
Пытался добавить в style.css - не помогло

**Comment by trydalcoholic** [comment]
Здравствуйте!
Вы можете изменять любые файлы шаблона. Убедитесь, что у вас отключено кэширование шаблонов в настройках OpenCart, а также обновите кэш модификаций.

**Comment by iron-zorin** [comment]
Я имел в виду, как добавить цвет, которого нет в палитре Materialize, чтобы его было возможно использовать через настройки.
Ответ: Никак. Палитра Materialize не расширяется.
