### ISSUE TITLE
Кнопка купить при недостатке товара

### ISSUE THREAD

**Issue by oggyden** [trydalcoholic/opencart-materialize#88]
Добрый день ак сделать кнопку добавить в корзину при отсутствии товара на складе?

**Comment by trydalcoholic** [comment]
Здравствуйте!
В соответствующих шаблонах вывода карточек товара удалите условия `{% if add_cart %}` и `{% if product.add_cart %}`, оставив вывод только активной кнопки без параметров `disabled="disabled"`.
Логика отключения кнопки была исправлена в новой разрабатываемой версии, подобная проблема больше возникать не будет.

**Comment by oggyden** [comment]
в новой версии кнопка так и не заработала?

**Comment by trydalcoholic** [comment]
Здравствуйте!
Речь шла о версии 0.81, данная версия всё ещё в разработке.
