### ISSUE TITLE
Проблемы с выпадающим меню "Категории"

### ISSUE THREAD

**Issue by Gennady365** [trydalcoholic/opencart-materialize#89]
На планшетах и смартфонах с большим разрешением, когда гамбургер выпадающего меню находится слева, меню при нажатии не раскрывается. Этот эффект также виден в Хроме, через Инструменты разработчика. Можно ли вообще отказаться от гамбургера и сделать горизонтальное меню для категорий товаров?

**Comment by trydalcoholic** [comment]
Здравствуйте!
Отредактируйте файл: `catalog/view/theme/materialize/js/script.js`
Найдите:
```
categoryDropdown.dropdown({
        hover: true,
        coverTrigger: false
    });
```
Измените параметр `hover `на `false`.
Вы можете вносить любые изменения в шаблон и сделать необходимое Вам меню.

**Comment by Gennady365** [comment]
Большое спасибо автору за помощь, и еще раз за отличную работу и впечатляющий шаблон.
