### ISSUE TITLE
Custom Colors Categories

### ISSUE THREAD

**Issue by Eddiecz** [trydalcoholic/opencart-materialize#90]
I can not find item in the template setting for category color change. Where to change? 

![open_cat](https://user-images.githubusercontent.com/4080487/43685215-3817eb92-98af-11e8-9d53-806048bde389.PNG)

**Comment by trydalcoholic** [comment]
Hello!
For the category module, you can only manually change the color. The category module in OpenCart is edited here: `catalog/view/theme/materialize/template/extension/module/category.twig`
